<?php
/**
 * sFire Framework (https://sfire.io)
 *
 * @link      https://github.com/sfire-framework/ for the canonical source repository
 * @copyright Copyright (c) 2014-2020 sFire Framework.
 * @license   http://sfire.io/license BSD 3-CLAUSE LICENSE
 */

declare(strict_types=1);

namespace sFire\Image\Color;

use sFire\Store\Container\ContainerAbstract;


/**
 * Class Catalog
 * @package sFire\Image
 */
class ColorCollection extends ContainerAbstract {


	/**
	 * Contains a list with colors
	 * @var array
	 */
	protected static array $data = [

        //All base colors
	    'base' => [

            0 => ['h' => '000000', 't' => 'black',],
            1 => ['h' => '844204', 't' => 'brown',],
            2 => ['h' => 'dc0000', 't' => 'red',],
            3 => ['h' => 'c752ff', 't' => 'purple',],
            4 => ['h' => 'db8f8d', 't' => 'pink',],
            5 => ['h' => '0099cc', 't' => 'blue',],
            6 => ['h' => 'ffff00', 't' => 'yellow',],
            7 => ['h' => 'feb42c', 't' => 'orange',],
            8 => ['h' => '949391', 't' => 'gray',],
            9 => ['h' => '3cd80d', 't' => 'green',],
            10 => ['h' => 'ffffff', 't' => 'white',]
        ],

        //All color shades
        'shades' => [

            0 => ['b' => 0, 'h' => '000000'],
            1 => ['b' => 1, 'h' => '3f1d0b'],
            2 => ['b' => 1, 'h' => '673e0f'],
            3 => ['b' => 1, 'h' => '844204'],
            4 => ['b' => 1, 'h' => '977254'],
            5 => ['b' => 1, 'h' => 'cfa76e'],
            6 => ['b' => 2, 'h' => '6b0000'],
            7 => ['b' => 2, 'h' => 'bb0000'],
            8 => ['b' => 2, 'h' => 'dc0000'],
            9 => ['b' => 2, 'h' => 'fe1a1a'],
            10 => ['b' => 2, 'h' => 'fe8585'],
            11 => ['b' => 3, 'h' => '410064'],
            12 => ['b' => 3, 'h' => '8700c9'],
            13 => ['b' => 3, 'h' => 'c752ff'],
            14 => ['b' => 3, 'h' => 'd98bff'],
            15 => ['b' => 3, 'h' => 'e9bffd'],
            16 => ['b' => 4, 'h' => 'c74275'],
            17 => ['b' => 4, 'h' => 'fb5393'],
            18 => ['b' => 4, 'h' => 'db8f8d'],
            19 => ['b' => 4, 'h' => 'f99abe'],
            20 => ['b' => 4, 'h' => 'fed6d9'],
            21 => ['b' => 5, 'h' => '013e7b'],
            22 => ['b' => 5, 'h' => '0066cc'],
            23 => ['b' => 5, 'h' => '0099cc'],
            24 => ['b' => 5, 'h' => '66cccc'],
            25 => ['b' => 5, 'h' => 'affbfb'],
            26 => ['b' => 6, 'h' => 'ffd800'],
            27 => ['b' => 6, 'h' => 'ffdf00'],
            28 => ['b' => 6, 'h' => 'ffff00'],
            29 => ['b' => 6, 'h' => 'ffee75'],
            30 => ['b' => 6, 'h' => 'fdf4b3'],
            31 => ['b' => 7, 'h' => 'e49401'],
            32 => ['b' => 7, 'h' => 'ffa500'],
            33 => ['b' => 7, 'h' => 'feb42c'],
            34 => ['b' => 7, 'h' => 'fdc765'],
            35 => ['b' => 7, 'h' => 'ffda97'],
            36 => ['b' => 8, 'h' => '433f40'],
            37 => ['b' => 8, 'h' => '726b68'],
            38 => ['b' => 8, 'h' => '949391'],
            39 => ['b' => 8, 'h' => 'c8c8c8'],
            40 => ['b' => 8, 'h' => 'e5e3e3'],
            41 => ['b' => 9, 'h' => '097829'],
            42 => ['b' => 9, 'h' => '2cae1e'],
            43 => ['b' => 9, 'h' => '3cd80d'],
            44 => ['b' => 9, 'h' => '1def5b'],
            45 => ['b' => 9, 'h' => '9dff89'],
            46 => ['b' => 10, 'h' => 'ffffff'],
        ],

        //All colors
        'colors' => [

            '101405' => ['s' => 0, 't' => 'Green Waterloo'],
            '130000' => ['s' => 0, 't' => 'Diesel'],
            '140600' => ['s' => 0, 't' => 'Nero'],
            '000000' => ['s' => 0, 't' => 'Black'],
            '000741' => ['s' => 0, 't' => 'Stratos'],
            '001b1c' => ['s' => 0, 't' => 'Swamp'],
            '010d1a' => ['s' => 0, 't' => 'Blue Charcoal'],
            '011635' => ['s' => 0, 't' => 'Midnight'],
            '011d13' => ['s' => 0, 't' => 'Holly'],
            '012731' => ['s' => 0, 't' => 'Daintree'],
            '03163c' => ['s' => 0, 't' => 'Tangaroa'],
            '041004' => ['s' => 0, 't' => 'Midnight Moss'],
            '041322' => ['s' => 0, 't' => 'Black Pearl'],
            '051040' => ['s' => 0, 't' => 'Deep Cove'],
            '080110' => ['s' => 0, 't' => 'Jaguar'],
            '081910' => ['s' => 0, 't' => 'Black Bean'],
            '0a001c' => ['s' => 0, 't' => 'Black Russian'],
            '0b0b0b' => ['s' => 0, 't' => 'Cod Gray'],
            '0b0f08' => ['s' => 0, 't' => 'Marshland'],
            '0b1107' => ['s' => 0, 't' => 'Gordons Green'],
            '0b1304' => ['s' => 0, 't' => 'Black Forest'],
            '0c0b1d' => ['s' => 0, 't' => 'Ebony'],
            '0c0d0f' => ['s' => 0, 't' => 'Woodsmoke'],
            '0c1911' => ['s' => 0, 't' => 'Racing Green'],
            '0d0332' => ['s' => 0, 't' => 'Black Rock'],
            '0d1117' => ['s' => 0, 't' => 'Bunker'],
            '0d1c19' => ['s' => 0, 't' => 'Aztec'],
            '0e0e18' => ['s' => 0, 't' => 'Cinder'],
            '10121d' => ['s' => 0, 't' => 'Vulcan'],
            '130a06' => ['s' => 0, 't' => 'Asphalt'],
            '161d10' => ['s' => 0, 't' => 'Hunter Green'],
            '171f04' => ['s' => 0, 't' => 'Pine Tree'],
            '1b1404' => ['s' => 0, 't' => 'Acadia'],
            '1c1208' => ['s' => 0, 't' => 'Crowshead'],
            '105852' => ['s' => 41, 't' => 'Eden'],
            '396413' => ['s' => 41, 't' => 'Dell'],
            '587156' => ['s' => 41, 't' => 'Cactus'],
            '002900' => ['s' => 41, 't' => 'Deep Fir'],
            '002e20' => ['s' => 41, 't' => 'Burnham'],
            '003532' => ['s' => 41, 't' => 'Deep Teal'],
            '004620' => ['s' => 41, 't' => 'Kaitoke Green'],
            '004816' => ['s' => 41, 't' => 'Crusoe'],
            '00581a' => ['s' => 41, 't' => 'Camarone'],
            '00755e' => ['s' => 41, 't' => 'Tropical Rain Forest'],
            '008080' => ['s' => 41, 't' => 'Teal'],
            '01361c' => ['s' => 41, 't' => 'Cardin Green'],
            '01371a' => ['s' => 41, 't' => 'County Green'],
            '014b43' => ['s' => 41, 't' => 'Aqua Deep'],
            '016162' => ['s' => 41, 't' => 'Blue Stone'],
            '016d39' => ['s' => 41, 't' => 'Fun Green'],
            '01796f' => ['s' => 41, 't' => 'Pine Green'],
            '01826b' => ['s' => 41, 't' => 'Deep Sea'],
            '022d15' => ['s' => 41, 't' => 'English Holly'],
            '02402c' => ['s' => 41, 't' => 'Sherwood Green'],
            '024e46' => ['s' => 41, 't' => 'Evening Sea'],
            '02866f' => ['s' => 41, 't' => 'Observatory'],
            '044022' => ['s' => 41, 't' => 'Zuccini'],
            '056f57' => ['s' => 41, 't' => 'Watercourse'],
            '088370' => ['s' => 41, 't' => 'Elf Green'],
            '09230f' => ['s' => 41, 't' => 'Palm Green'],
            '095859' => ['s' => 41, 't' => 'Deep Sea Green'],
            '097f4b' => ['s' => 41, 't' => 'Salem'],
            '0a480d' => ['s' => 41, 't' => 'Dark Fern'],
            '0a6906' => ['s' => 41, 't' => 'Japanese Laurel'],
            '0a6f75' => ['s' => 41, 't' => 'Atoll'],
            '0b6207' => ['s' => 41, 't' => 'San Felix'],
            '0d2e1c' => ['s' => 41, 't' => 'Bush'],
            '126b40' => ['s' => 41, 't' => 'Jewel'],
            '134f19' => ['s' => 41, 't' => 'Parsley'],
            '15736b' => ['s' => 41, 't' => 'Genoa'],
            '1c7c7d' => ['s' => 41, 't' => 'Elm'],
            '1d6142' => ['s' => 41, 't' => 'Green Pea'],
            '228b22' => ['s' => 41, 't' => 'Forest Green'],
            '24500f' => ['s' => 41, 't' => 'Green House'],
            '278a5b' => ['s' => 41, 't' => 'Eucalyptus'],
            '2e8b57' => ['s' => 41, 't' => 'Sea Green'],
            '327c14' => ['s' => 41, 't' => 'Bilbao'],
            '368716' => ['s' => 42, 't' => 'La Palma'],
            '549019' => ['s' => 42, 't' => 'Vida Loca'],
            '578363' => ['s' => 42, 't' => 'Spring Leaves'],
            '749378' => ['s' => 42, 't' => 'Laurel'],
            '819885' => ['s' => 42, 't' => 'Spanish Green'],
            '00a86b' => ['s' => 42, 't' => 'Jade'],
            '01a368' => ['s' => 42, 't' => 'Green Haze'],
            '1ab385' => ['s' => 42, 't' => 'Mountain Meadow'],
            '29ab87' => ['s' => 42, 't' => 'Jungle Green'],
            '40a860' => ['s' => 42, 't' => 'Chateau Green'],
            '4fa83d' => ['s' => 42, 't' => 'Apple'],
            '5fa777' => ['s' => 42, 't' => 'Aqua Forest'],
            '63b76c' => ['s' => 42, 't' => 'Fern'],
            '67a712' => ['s' => 42, 't' => 'Christi'],
            '6b8e23' => ['s' => 42, 't' => 'Olive Drab'],
            '6f9d02' => ['s' => 42, 't' => 'Limeade'],
            '83aa5d' => ['s' => 42, 't' => 'Chelsea Cucumber'],
            '00ff00' => ['s' => 45, 't' => 'Green'],
            '00ff7f' => ['s' => 45, 't' => 'Spring Green'],
            '3fff00' => ['s' => 45, 't' => 'Harlequin'],
            '66ff00' => ['s' => 45, 't' => 'Bright Green'],
            '66ff66' => ['s' => 45, 't' => 'Screamin\' Green'],
            '77dd77' => ['s' => 45, 't' => 'Pastel Green'],
            '7fff00' => ['s' => 45, 't' => 'Chartreuse'],
            '98ff98' => ['s' => 45, 't' => 'Mint Green'],
            '9ab973' => ['s' => 45, 't' => 'Olivine'],
            '9de093' => ['s' => 45, 't' => 'Granny Smith Apple'],
            '9fdd8c' => ['s' => 45, 't' => 'Feijoa'],
            'acdd4d' => ['s' => 45, 't' => 'Conifer'],
            'adff2f' => ['s' => 45, 't' => 'Green Yellow'],
            'bfff00' => ['s' => 45, 't' => 'Lime'],
            'c1f07c' => ['s' => 45, 't' => 'Sulu'],
            'c5e17a' => ['s' => 45, 't' => 'Yellow Green'],
            'c9ffa2' => ['s' => 45, 't' => 'Reef'],
            'ccff00' => ['s' => 45, 't' => 'Electric Lime'],
            '0bda51' => ['s' => 44, 't' => 'Malachite'],
            'b0e313' => ['s' => 44, 't' => 'Inch Worm'],
            '50c878' => ['s' => 43, 't' => 'Emerald'],
            '66b58f' => ['s' => 43, 't' => 'Silver Tree'],
            '74c365' => ['s' => 43, 't' => 'Mantis'],
            '76bd17' => ['s' => 43, 't' => 'Lima'],
            '7ac488' => ['s' => 43, 't' => 'De York'],
            '9dc209' => ['s' => 43, 't' => 'Pistachio'],
            'a1c50a' => ['s' => 43, 't' => 'Citrus'],
            'a5cb0c' => ['s' => 43, 't' => 'Bahia'],
            'bfc921' => ['s' => 43, 't' => 'Key Lime Pie'],
            '123447' => ['s' => 21, 't' => 'Elephant'],
            '175579' => ['s' => 21, 't' => 'Chathams Blue'],
            '000080' => ['s' => 21, 't' => 'Navy Blue'],
            '002387' => ['s' => 21, 't' => 'Resolution Blue'],
            '003153' => ['s' => 21, 't' => 'Prussian Blue'],
            '003366' => ['s' => 21, 't' => 'Midnight Blue'],
            '003399' => ['s' => 21, 't' => 'Smalt'],
            '003e40' => ['s' => 21, 't' => 'Cyprus'],
            '004950' => ['s' => 21, 't' => 'Sherpa Blue'],
            '013e62' => ['s' => 21, 't' => 'Astronaut Blue'],
            '013f6a' => ['s' => 21, 't' => 'Regal Blue'],
            '017987' => ['s' => 21, 't' => 'Blue Lagoon'],
            '02478e' => ['s' => 21, 't' => 'Congress Blue'],
            '026395' => ['s' => 21, 't' => 'Bahama Blue'],
            '032b52' => ['s' => 21, 't' => 'Green Vogue'],
            '036a6e' => ['s' => 21, 't' => 'Mosque'],
            '042e4c' => ['s' => 21, 't' => 'Blue Whale'],
            '044259' => ['s' => 21, 't' => 'Teal Blue'],
            '051657' => ['s' => 21, 't' => 'Gulf Blue'],
            '062a78' => ['s' => 21, 't' => 'Catalina Blue'],
            '073a50' => ['s' => 21, 't' => 'Tarawera'],
            '082567' => ['s' => 21, 't' => 'Deep Sapphire'],
            '092256' => ['s' => 21, 't' => 'Downriver'],
            '09255d' => ['s' => 21, 't' => 'Madison'],
            '0c7a79' => ['s' => 21, 't' => 'Surfie Green'],
            '0f2d9e' => ['s' => 21, 't' => 'Torea Bay'],
            '120a8f' => ['s' => 21, 't' => 'Ultramarine'],
            '13264d' => ['s' => 21, 't' => 'Blue Zodiac'],
            '18587a' => ['s' => 21, 't' => 'Blumine'],
            '1b3162' => ['s' => 21, 't' => 'Biscay'],
            '1e385b' => ['s' => 21, 't' => 'Cello'],
            '20208d' => ['s' => 21, 't' => 'Jacksons Purple'],
            '273a81' => ['s' => 21, 't' => 'Bay of Many'],
            '283a77' => ['s' => 21, 't' => 'Astronaut'],
            '2d569b' => ['s' => 21, 't' => 'St Tropaz'],
            '2f519e' => ['s' => 21, 't' => 'Sapphire'],
            '31728d' => ['s' => 21, 't' => 'Calypso'],
            '354e8c' => ['s' => 21, 't' => 'Chambray'],
            '377475' => ['s' => 23, 't' => 'Oracle'],
            '0095b6' => ['s' => 23, 't' => 'Bondi Blue'],
            '009dc4' => ['s' => 23, 't' => 'Pacific Blue'],
            '00a693' => ['s' => 23, 't' => 'Persian Green'],
            '00cc99' => ['s' => 23, 't' => 'Caribbean Green'],
            '00cccc' => ['s' => 23, 't' => 'Robin\'s Egg Blue'],
            '00ffff' => ['s' => 23, 't' => 'Cyan / Aqua'],
            '02a4d3' => ['s' => 23, 't' => 'Cerulean'],
            '069b81' => ['s' => 23, 't' => 'Gossamer'],
            '06a189' => ['s' => 23, 't' => 'Niagara'],
            '08e8de' => ['s' => 23, 't' => 'Bright Turquoise'],
            '0c8990' => ['s' => 23, 't' => 'Blue Chill'],
            '1e90ff' => ['s' => 23, 't' => 'Dodger Blue'],
            '1e9ab0' => ['s' => 23, 't' => 'Eastern Blue'],
            '1fc2c2' => ['s' => 23, 't' => 'Java'],
            '2596d1' => ['s' => 23, 't' => 'Curious Blue'],
            '3b91b4' => ['s' => 23, 't' => 'Boston Blue'],
            '4682b4' => ['s' => 23, 't' => 'Steel Blue'],
            '788bba' => ['s' => 23, 't' => 'Ship Cove'],
            '7a89b8' => ['s' => 23, 't' => 'Wild Blue Yonder'],
            '8581d9' => ['s' => 23, 't' => 'Chetwode Blue'],
            '427977' => ['s' => 24, 't' => 'Faded Jade'],
            '2ebfd4' => ['s' => 24, 't' => 'Scooter'],
            '30d5c8' => ['s' => 24, 't' => 'Turquoise'],
            '33cc99' => ['s' => 24, 't' => 'Shamrock'],
            '3ab09e' => ['s' => 24, 't' => 'Keppel'],
            '3eabbf' => ['s' => 24, 't' => 'Pelorous'],
            '3fc1aa' => ['s' => 24, 't' => 'Puerto Rico'],
            '45b1e8' => ['s' => 24, 't' => 'Picton Blue'],
            '4eabd1' => ['s' => 24, 't' => 'Shakespeare'],
            '5590d9' => ['s' => 24, 't' => 'Havelock Blue'],
            '56b4be' => ['s' => 24, 't' => 'Fountain Blue'],
            '589aaf' => ['s' => 24, 't' => 'Hippie Blue'],
            '5da19f' => ['s' => 24, 't' => 'Breaker Bay'],
            '5fb3ac' => ['s' => 24, 't' => 'Tradewind'],
            '6093d1' => ['s' => 24, 't' => 'Danube'],
            '6495ed' => ['s' => 24, 't' => 'Cornflower Blue'],
            '64ccdb' => ['s' => 24, 't' => 'Viking'],
            '6cdae7' => ['s' => 24, 't' => 'Turquoise Blue'],
            '6fd0c5' => ['s' => 24, 't' => 'Downy'],
            '71d9e2' => ['s' => 24, 't' => 'Aquamarine Blue'],
            '76d7ea' => ['s' => 24, 't' => 'Sky Blue'],
            '79deec' => ['s' => 24, 't' => 'Spray'],
            '7cb7bb' => ['s' => 24, 't' => 'Neptune'],
            '7dc8f7' => ['s' => 24, 't' => 'Malibu'],
            '7dd8c6' => ['s' => 24, 't' => 'Bermuda'],
            '7fffd4' => ['s' => 24, 't' => 'Aquamarine'],
            '80b3ae' => ['s' => 24, 't' => 'Gulf Stream'],
            '80b3c4' => ['s' => 24, 't' => 'Glacier'],
            '80ccea' => ['s' => 24, 't' => 'Seagull'],
            '83d0c6' => ['s' => 24, 't' => 'Monte Carlo'],
            '85c4cc' => ['s' => 24, 't' => 'Half Baked'],
            '8ab9f1' => ['s' => 24, 't' => 'Jordy Blue'],
            '8b9fee' => ['s' => 24, 't' => 'Portage'],
            '8be6d8' => ['s' => 24, 't' => 'Riptide'],
            '8da8cc' => ['s' => 24, 't' => 'Polo Blue'],
            '8eabc1' => ['s' => 24, 't' => 'Nepal'],
            '8fd6b4' => ['s' => 24, 't' => 'Vista Blue'],
            '93ccea' => ['s' => 24, 't' => 'Cornflower'],
            '93dfb8' => ['s' => 24, 't' => 'Algae Green'],
            '496679' => ['s' => 22, 't' => 'Blue Bayoux'],
            '497183' => ['s' => 22, 't' => 'Bismark'],
            '507096' => ['s' => 22, 't' => 'Kashmir Blue'],
            '0000c8' => ['s' => 22, 't' => 'Dark Blue'],
            '0000ff' => ['s' => 22, 't' => 'Blue'],
            '002fa7' => ['s' => 22, 't' => 'International Klein Blue'],
            '0047ab' => ['s' => 22, 't' => 'Cobalt'],
            '0056a7' => ['s' => 22, 't' => 'Endeavour'],
            '0066cc' => ['s' => 22, 't' => 'Science Blue'],
            '0066ff' => ['s' => 22, 't' => 'Blue Ribbon'],
            '0076a3' => ['s' => 22, 't' => 'Allports'],
            '007ba7' => ['s' => 22, 't' => 'Deep Cerulean'],
            '007ec7' => ['s' => 22, 't' => 'Lochmara'],
            '007fff' => ['s' => 22, 't' => 'Azure Radiance'],
            '015e85' => ['s' => 22, 't' => 'Orient'],
            '055989' => ['s' => 22, 't' => 'Venice Blue'],
            '1450aa' => ['s' => 22, 't' => 'Tory Blue'],
            '1560bd' => ['s' => 22, 't' => 'Denim'],
            '1959a8' => ['s' => 22, 't' => 'Fun Blue'],
            '1b659d' => ['s' => 22, 't' => 'Matisse'],
            '1c39bb' => ['s' => 22, 't' => 'Persian Blue'],
            '286acd' => ['s' => 22, 't' => 'Mariner'],
            '297b9a' => ['s' => 22, 't' => 'Jelly Bean'],
            '2a52be' => ['s' => 22, 't' => 'Cerulean Blue'],
            '2f3cb3' => ['s' => 22, 't' => 'Governor Bay'],
            '315ba1' => ['s' => 22, 't' => 'Azure'],
            '327da0' => ['s' => 22, 't' => 'Astral'],
            '4169e1' => ['s' => 22, 't' => 'Royal Blue'],
            '456cac' => ['s' => 22, 't' => 'San Marino'],
            '4f69c6' => ['s' => 22, 't' => 'Indigo'],
            '5a87a0' => ['s' => 22, 't' => 'Horizon'],
            '65869f' => ['s' => 22, 't' => 'Hoki'],
            '697e9a' => ['s' => 22, 't' => 'Lynch'],
            '9de5ff' => ['s' => 25, 't' => 'Anakiwa'],
            '9edee0' => ['s' => 25, 't' => 'Morning Glory'],
            'a1e9de' => ['s' => 25, 't' => 'Water Leaf'],
            'a3e3ed' => ['s' => 25, 't' => 'Blizzard Blue'],
            'aad6e6' => ['s' => 25, 't' => 'Regent St Blue'],
            'aaf0d1' => ['s' => 25, 't' => 'Magic Mint'],
            'b0e0e6' => ['s' => 25, 't' => 'Powder Blue'],
            'b1f4e7' => ['s' => 25, 't' => 'Ice Cold'],
            'b5ecdf' => ['s' => 25, 't' => 'Cruise'],
            'b8e0f9' => ['s' => 25, 't' => 'Sail'],
            'baeef9' => ['s' => 25, 't' => 'Charlotte'],
            'bdedfd' => ['s' => 25, 't' => 'French Pass'],
            'c2e8e5' => ['s' => 25, 't' => 'Jagged Ice'],
            'c3ddf9' => ['s' => 25, 't' => 'Tropical Blue'],
            'c4f4eb' => ['s' => 25, 't' => 'Mint Tulip'],
            'c9ffe5' => ['s' => 25, 't' => 'Aero Blue'],
            'cdf4ff' => ['s' => 25, 't' => 'Onahau'],
            'cff9f3' => ['s' => 25, 't' => 'Humming Bird'],
            'cffaf4' => ['s' => 25, 't' => 'Scandal'],
            '808000' => ['s' => 3, 't' => 'Olive'],
            '886221' => ['s' => 3, 't' => 'Kumera'],
            '924321' => ['s' => 3, 't' => 'Cumin'],
            '74640d' => ['s' => 3, 't' => 'Spicy Mustard'],
            '7b3801' => ['s' => 3, 't' => 'Red Beech'],
            '7b3f00' => ['s' => 3, 't' => 'Cinnamon'],
            '7b6608' => ['s' => 3, 't' => 'Yukon Gold'],
            '7d2c14' => ['s' => 3, 't' => 'Pueblo'],
            '7e3a15' => ['s' => 3, 't' => 'Copper Canyon'],
            '7f3a02' => ['s' => 3, 't' => 'Peru Tan'],
            '80341f' => ['s' => 3, 't' => 'Red Robin'],
            '80461b' => ['s' => 3, 't' => 'Russet'],
            '864d1e' => ['s' => 3, 't' => 'Bull Shot'],
            '86560a' => ['s' => 3, 't' => 'Rusty Nail'],
            '8a3324' => ['s' => 3, 't' => 'Burnt Umber'],
            '8b6b0b' => ['s' => 3, 't' => 'Corn Harvest'],
            '8c472f' => ['s' => 3, 't' => 'Mule Fawn'],
            '8d3d38' => ['s' => 3, 't' => 'Sanguine Brown'],
            '8e4d1e' => ['s' => 3, 't' => 'Rope'],
            '8f3e33' => ['s' => 3, 't' => 'El Salva'],
            '8f4b0e' => ['s' => 3, 't' => 'Korma'],
            '901e1e' => ['s' => 3, 't' => 'Old Brick'],
            '964b00' => ['s' => 3, 't' => 'Brown'],
            '9a3820' => ['s' => 3, 't' => 'Prairie Sand'],
            '9b4703' => ['s' => 3, 't' => 'Oregon'],
            '9c3336' => ['s' => 3, 't' => 'Stiletto'],
            '9d5616' => ['s' => 3, 't' => 'Hawaiian Tan'],
            '9e5302' => ['s' => 3, 't' => 'Chelsea Gem'],
            '9f381d' => ['s' => 3, 't' => 'Cognac'],
            'a02712' => ['s' => 3, 't' => 'Tabasco'],
            'a1750d' => ['s' => 3, 't' => 'Buttered Rum'],
            'a62f20' => ['s' => 3, 't' => 'Roof Terracotta'],
            'a65529' => ['s' => 3, 't' => 'Paarl'],
            'a85307' => ['s' => 3, 't' => 'Rich Gold'],
            'a86515' => ['s' => 3, 't' => 'Reno Sand'],
            'aa4203' => ['s' => 3, 't' => 'Fire'],
            'ae6020' => ['s' => 3, 't' => 'Desert'],
            'b06608' => ['s' => 3, 't' => 'Mai Tai'],
            'b14a0b' => ['s' => 3, 't' => 'Vesuvius'],
            'b1610b' => ['s' => 3, 't' => 'Pumpkin Skin'],
            'b35213' => ['s' => 3, 't' => 'Fiery Orange'],
            'b43332' => ['s' => 3, 't' => 'Well Read'],
            'b7410e' => ['s' => 3, 't' => 'Rust'],
            'ba450c' => ['s' => 3, 't' => 'Rock Spray'],
            'bf5500' => ['s' => 3, 't' => 'Rose of Sharon'],
            'c1440e' => ['s' => 3, 't' => 'Tia Maria'],
            'c45719' => ['s' => 3, 't' => 'Orange Roughy'],
            '737829' => ['s' => 4, 't' => 'Crete'],
            '778120' => ['s' => 4, 't' => 'Pacifika'],
            '837050' => ['s' => 4, 't' => 'Shadow'],
            '885342' => ['s' => 4, 't' => 'Spicy Mix'],
            '893843' => ['s' => 4, 't' => 'Solid Pink'],
            '907874' => ['s' => 4, 't' => 'Hemp'],
            '928573' => ['s' => 4, 't' => 'Stonewall'],
            '944747' => ['s' => 4, 't' => 'Copper Rust'],
            '948771' => ['s' => 4, 't' => 'Arrowtown'],
            '967059' => ['s' => 4, 't' => 'Leather'],
            '996666' => ['s' => 4, 't' => 'Copper Rose'],
            '788a25' => ['s' => 4, 't' => 'Wasabi'],
            '7ba05b' => ['s' => 4, 't' => 'Asparagus'],
            '7c7631' => ['s' => 4, 't' => 'Pesto'],
            '7c881a' => ['s' => 4, 't' => 'Trendy Green'],
            '86483c' => ['s' => 4, 't' => 'Ironstone'],
            '87ab39' => ['s' => 4, 't' => 'Sushi'],
            '888d65' => ['s' => 4, 't' => 'Avocado'],
            '8a8360' => ['s' => 4, 't' => 'Clay Creek'],
            '8b8470' => ['s' => 4, 't' => 'Olive Haze'],
            '8c5738' => ['s' => 4, 't' => 'Potters Clay'],
            '8d3f3f' => ['s' => 4, 't' => 'Tosca'],
            '8d7662' => ['s' => 4, 't' => 'Cement'],
            '8e775e' => ['s' => 4, 't' => 'Domino'],
            '907b71' => ['s' => 4, 't' => 'Almond Frost'],
            '908d39' => ['s' => 4, 't' => 'Sycamore'],
            '926f5b' => ['s' => 4, 't' => 'Beaver'],
            '97605d' => ['s' => 4, 't' => 'Au Chico'],
            '98811b' => ['s' => 4, 't' => 'Hacienda'],
            '9a6e61' => ['s' => 4, 't' => 'Toast'],
            '9e5b40' => ['s' => 4, 't' => 'Sepia Skin'],
            '9ea91f' => ['s' => 4, 't' => 'Citron'],
            '9f821c' => ['s' => 4, 't' => 'Reef Gold'],
            'a26645' => ['s' => 4, 't' => 'Cape Palliser'],
            'a68b5b' => ['s' => 4, 't' => 'Barley Corn'],
            'a7882c' => ['s' => 4, 't' => 'Luxor Gold'],
            'a86b6b' => ['s' => 4, 't' => 'Coral Tree'],
            'aa8b5b' => ['s' => 4, 't' => 'Muesli'],
            'aa8d6f' => ['s' => 4, 't' => 'Sandal'],
            'ac8a56' => ['s' => 4, 't' => 'Limed Oak'],
            'ad781b' => ['s' => 4, 't' => 'Mandalay'],
            'af4035' => ['s' => 4, 't' => 'Medium Carmine'],
            'af4d43' => ['s' => 4, 't' => 'Apple Blossom'],
            'af593e' => ['s' => 4, 't' => 'Brown Rust'],
            'af8751' => ['s' => 4, 't' => 'Driftwood'],
            'af8f2c' => ['s' => 4, 't' => 'Alpine'],
            'b05d54' => ['s' => 4, 't' => 'Matrix'],
            'b16d52' => ['s' => 4, 't' => 'Santa Fe'],
            'b87333' => ['s' => 4, 't' => 'Copper'],
            'b95140' => ['s' => 4, 't' => 'Crail'],
            'bd5e2e' => ['s' => 4, 't' => 'Tuscany'],
            '161928' => ['s' => 1, 't' => 'Mirage'],
            '163222' => ['s' => 1, 't' => 'Celtic'],
            '233418' => ['s' => 1, 't' => 'Mallard'],
            '251607' => ['s' => 1, 't' => 'Graphite'],
            '251706' => ['s' => 1, 't' => 'Cannon Black'],
            '261105' => ['s' => 1, 't' => 'Wood Bark'],
            '261414' => ['s' => 1, 't' => 'Gondola'],
            '292319' => ['s' => 1, 't' => 'Zeus'],
            '300529' => ['s' => 1, 't' => 'Melanzane'],
            '341515' => ['s' => 1, 't' => 'Tamarind'],
            '370202' => ['s' => 1, 't' => 'Chocolate'],
            '373021' => ['s' => 1, 't' => 'Birch'],
            '384910' => ['s' => 1, 't' => 'Clover'],
            '401801' => ['s' => 1, 't' => 'Brown Pod'],
            '412010' => ['s' => 1, 't' => 'Deep Oak'],
            '420303' => ['s' => 1, 't' => 'Burnt Maroon'],
            '433120' => ['s' => 1, 't' => 'Iroko'],
            '462425' => ['s' => 1, 't' => 'Crater Brown'],
            '480404' => ['s' => 1, 't' => 'Rustic Red'],
            '480607' => ['s' => 1, 't' => 'Bulgarian Rose'],
            '492615' => ['s' => 1, 't' => 'Brown Derby'],
            '541012' => ['s' => 1, 't' => 'Heath'],
            '093624' => ['s' => 1, 't' => 'Bottle Green'],
            '182d09' => ['s' => 1, 't' => 'Deep Forest Green'],
            '19330e' => ['s' => 1, 't' => 'Palm Leaf'],
            '1b1035' => ['s' => 1, 't' => 'Haiti'],
            '1b2f11' => ['s' => 1, 't' => 'Seaweed'],
            '1c1e13' => ['s' => 1, 't' => 'Rangoon Green'],
            '1e0f04' => ['s' => 1, 't' => 'Creole'],
            '1e1609' => ['s' => 1, 't' => 'Karaka'],
            '1e1708' => ['s' => 1, 't' => 'El Paso'],
            '1f120f' => ['s' => 1, 't' => 'Night Rider'],
            '211a0e' => ['s' => 1, 't' => 'Eternity'],
            '240c02' => ['s' => 1, 't' => 'Kilamanjaro'],
            '242a1d' => ['s' => 1, 't' => 'Log Cabin'],
            '242e16' => ['s' => 1, 't' => 'Black Olive'],
            '25272c' => ['s' => 1, 't' => 'Shark'],
            '25311c' => ['s' => 1, 't' => 'Green Kelp'],
            '281e15' => ['s' => 1, 't' => 'Oil'],
            '2a140e' => ['s' => 1, 't' => 'Coffee Bean'],
            '2a380b' => ['s' => 1, 't' => 'Turtle Green'],
            '2b0202' => ['s' => 1, 't' => 'Sepia Black'],
            '2c1632' => ['s' => 1, 't' => 'Revolver'],
            '2d2510' => ['s' => 1, 't' => 'Mikado'],
            '2e0329' => ['s' => 1, 't' => 'Jacaranda'],
            '2e1905' => ['s' => 1, 't' => 'Jacko Bean'],
            '2e3222' => ['s' => 1, 't' => 'Rangitoto'],
            '2f270e' => ['s' => 1, 't' => 'Onion'],
            '301f1e' => ['s' => 1, 't' => 'Cocoa Brown'],
            '302a0f' => ['s' => 1, 't' => 'Woodrush'],
            '311c17' => ['s' => 1, 't' => 'Eclipse'],
            '363c0d' => ['s' => 1, 't' => 'Waiouru'],
            '371d09' => ['s' => 1, 't' => 'Clinker'],
            '37290e' => ['s' => 1, 't' => 'Brown Tumbleweed'],
            '3a0020' => ['s' => 1, 't' => 'Toledo'],
            '3a2010' => ['s' => 1, 't' => 'Sambuca'],
            '3b000b' => ['s' => 1, 't' => 'Temptress'],
            '3b0910' => ['s' => 1, 't' => 'Aubergine'],
            '3b1f1f' => ['s' => 1, 't' => 'Jon'],
            '3b2820' => ['s' => 1, 't' => 'Treehouse'],
            '3c1206' => ['s' => 1, 't' => 'Rebel'],
            '3c2005' => ['s' => 1, 't' => 'Dark Ebony'],
            '3c3910' => ['s' => 1, 't' => 'Camouflage'],
            '3d0c02' => ['s' => 1, 't' => 'Bean  '],
            '3d2b1f' => ['s' => 1, 't' => 'Bistre'],
            '3e1c14' => ['s' => 1, 't' => 'Cedar'],
            '3e2b23' => ['s' => 1, 't' => 'English Walnut'],
            '3e2c1c' => ['s' => 1, 't' => 'Black Marlin'],
            '3f2109' => ['s' => 1, 't' => 'Bronze'],
            '3f2500' => ['s' => 1, 't' => 'Cola'],
            '3f3002' => ['s' => 1, 't' => 'Madras'],
            '40291d' => ['s' => 1, 't' => 'Cork'],
            '403d19' => ['s' => 1, 't' => 'Thatch Green'],
            '411f10' => ['s' => 1, 't' => 'Paco'],
            '44012d' => ['s' => 1, 't' => 'Barossa'],
            '441d00' => ['s' => 1, 't' => 'Morocco Brown'],
            '481c1c' => ['s' => 1, 't' => 'Cocoa Bean'],
            '49170c' => ['s' => 1, 't' => 'Van Cleef'],
            '49371b' => ['s' => 1, 't' => 'Metallic Bronze'],
            '4a2a04' => ['s' => 1, 't' => 'Bracken'],
            '4a3004' => ['s' => 1, 't' => 'Deep Bronze'],
            '4d0a18' => ['s' => 1, 't' => 'Cab Sav'],
            '4d1e01' => ['s' => 1, 't' => 'Indian Tan'],
            '4e0606' => ['s' => 1, 't' => 'Mahogany'],
            '520c17' => ['s' => 1, 't' => 'Maroon Oak'],
            '55280c' => ['s' => 1, 't' => 'Cioccolato'],
            '5d1e0f' => ['s' => 1, 't' => 'Redwood'],
            '495400' => ['s' => 2, 't' => 'Verdun Green'],
            '583401' => ['s' => 2, 't' => 'Saddle Brown'],
            '592804' => ['s' => 2, 't' => 'Brown Bramble'],
            '604913' => ['s' => 2, 't' => 'Horses Neck'],
            '612718' => ['s' => 2, 't' => 'Espresso'],
            '625119' => ['s' => 2, 't' => 'West Coast'],
            '657220' => ['s' => 2, 't' => 'Fern Frond'],
            '683600' => ['s' => 2, 't' => 'Nutmeg Wood Finish'],
            '704214' => ['s' => 2, 't' => 'Sepia'],
            '436a0d' => ['s' => 2, 't' => 'Green Leaf'],
            '4d3d14' => ['s' => 2, 't' => 'Punga'],
            '4d400f' => ['s' => 2, 't' => 'Bronzetone'],
            '4e420c' => ['s' => 2, 't' => 'Bronze Olive'],
            '555b10' => ['s' => 2, 't' => 'Saratoga'],
            '5b3013' => ['s' => 2, 't' => 'Jambalaya'],
            '5c2e01' => ['s' => 2, 't' => 'Carnaby Tan'],
            '5f3d26' => ['s' => 2, 't' => 'Irish Coffee'],
            '622f30' => ['s' => 2, 't' => 'Buccaneer'],
            '623f2d' => ['s' => 2, 't' => 'Quincy'],
            '6a442e' => ['s' => 2, 't' => 'Spice'],
            '6a5d1b' => ['s' => 2, 't' => 'Himalaya'],
            '6b2a14' => ['s' => 2, 't' => 'Hairy Heath'],
            '6b4e31' => ['s' => 2, 't' => 'Shingle Fawn'],
            '6e1d14' => ['s' => 2, 't' => 'Moccaccino'],
            '6e4826' => ['s' => 2, 't' => 'Pickled Bean'],
            '6e4b26' => ['s' => 2, 't' => 'Dallas'],
            '6f440c' => ['s' => 2, 't' => 'Cafe Royale'],
            '701c1c' => ['s' => 2, 't' => 'Persian Plum'],
            '704a07' => ['s' => 2, 't' => 'Antique Bronze'],
            '71291d' => ['s' => 2, 't' => 'Metallic Copper'],
            '716e10' => ['s' => 2, 't' => 'Olivetone'],
            '724a2f' => ['s' => 2, 't' => 'Old Copper'],
            '734a12' => ['s' => 2, 't' => 'Raw Umber'],
            '771f1f' => ['s' => 2, 't' => 'Crown of Thorns'],
            '773f1a' => ['s' => 2, 't' => 'Walnut'],
            '782d19' => ['s' => 2, 't' => 'Mocha'],
            '782f16' => ['s' => 2, 't' => 'Peanut'],
            '7f1734' => ['s' => 2, 't' => 'Claret'],
            '81422c' => ['s' => 2, 't' => 'Nutmeg'],
            '863c3c' => ['s' => 2, 't' => 'Lotus'],
            '97cd2d' => ['s' => 5, 't' => 'Atlantis'],
            'a4af6e' => ['s' => 5, 't' => 'Green Smoke'],
            'a69279' => ['s' => 5, 't' => 'Donkey Brown'],
            'ab917a' => ['s' => 5, 't' => 'Sandrift'],
            'b19461' => ['s' => 5, 't' => 'Teak'],
            'b5a27f' => ['s' => 5, 't' => 'Mongoose'],
            'b5b35c' => ['s' => 5, 't' => 'Olive Green'],
            'b78e5c' => ['s' => 5, 't' => 'Muddy Waters'],
            'b7a458' => ['s' => 5, 't' => 'Husk'],
            'b8b56a' => ['s' => 5, 't' => 'Gimblet'],
            'b8c25d' => ['s' => 5, 't' => 'Celery'],
            'b9c46a' => ['s' => 5, 't' => 'Wild Willow'],
            'c2955d' => ['s' => 5, 't' => 'Twine'],
            'c3b091' => ['s' => 5, 't' => 'Indian Khaki'],
            'c5994b' => ['s' => 5, 't' => 'Tussock'],
            'c6a84b' => ['s' => 5, 't' => 'Roti'],
            'c7cd90' => ['s' => 5, 't' => 'Pine Glade'],
            'c88a65' => ['s' => 5, 't' => 'Antique Brass'],
            'c8b568' => ['s' => 5, 't' => 'Laser'],
            'c9b35b' => ['s' => 5, 't' => 'Sundance'],
            'c9b93b' => ['s' => 5, 't' => 'Earls Green'],
            'cabb48' => ['s' => 5, 't' => 'Turmeric'],
            'ceb98f' => ['s' => 5, 't' => 'Sorrell Brown'],
            'cec291' => ['s' => 5, 't' => 'Yuma'],
            'd27d46' => ['s' => 5, 't' => 'Raw Sienna'],
            'd2b48c' => ['s' => 5, 't' => 'Tan'],
            'd4bf8d' => ['s' => 5, 't' => 'Straw'],
            'd59a6f' => ['s' => 5, 't' => 'Whiskey'],
            'd6c562' => ['s' => 5, 't' => 'Tacha'],
            'd87c63' => ['s' => 5, 't' => 'Japonica'],
            'da8a67' => ['s' => 5, 't' => 'Copperfield'],
            'db995e' => ['s' => 5, 't' => 'Di Serria'],
            'dea681' => ['s' => 5, 't' => 'Tumbleweed'],
            'dfbe6f' => ['s' => 5, 't' => 'Apache'],
            'e0b974' => ['s' => 5, 't' => 'Harvest Gold'],
            'e1bc64' => ['s' => 5, 't' => 'Equator'],
            'eaae69' => ['s' => 5, 't' => 'Porsche'],
            'edb381' => ['s' => 5, 't' => 'Tacao'],
            '708090' => ['s' => 38, 't' => 'Slate Gray'],
            '748881' => ['s' => 38, 't' => 'Blue Smoke'],
            '808080' => ['s' => 38, 't' => 'Gray'],
            '828685' => ['s' => 38, 't' => 'Gunsmoke'],
            '868974' => ['s' => 38, 't' => 'Bitter'],
            '888387' => ['s' => 38, 't' => 'Suva Gray'],
            '928590' => ['s' => 38, 't' => 'Venus'],
            '959396' => ['s' => 38, 't' => 'Mountain Mist'],
            '639a8f' => ['s' => 38, 't' => 'Patina'],
            '6b8ba2' => ['s' => 38, 't' => 'Bermuda Gray'],
            '6d9292' => ['s' => 38, 't' => 'Juniper'],
            '6d92a1' => ['s' => 38, 't' => 'Gothic'],
            '779e86' => ['s' => 38, 't' => 'Oxley'],
            '78a39c' => ['s' => 38, 't' => 'Sea Nymph'],
            '7b7c94' => ['s' => 38, 't' => 'Waterloo '],
            '7b9f80' => ['s' => 38, 't' => 'Amulet'],
            '7ca1a6' => ['s' => 38, 't' => 'Gumbo'],
            '7cb0a1' => ['s' => 38, 't' => 'Acapulco'],
            '7da98d' => ['s' => 38, 't' => 'Bay Leaf'],
            '828f72' => ['s' => 38, 't' => 'Battleship Gray'],
            '84a0a0' => ['s' => 38, 't' => 'Granny Smith'],
            '859faf' => ['s' => 38, 't' => 'Bali Hai'],
            '86949f' => ['s' => 38, 't' => 'Regent Gray'],
            '878d91' => ['s' => 38, 't' => 'Oslo Gray'],
            '8a8389' => ['s' => 38, 't' => 'Monsoon'],
            '8a8f8a' => ['s' => 38, 't' => 'Stack'],
            '8b847e' => ['s' => 38, 't' => 'Schooner'],
            '8b8680' => ['s' => 38, 't' => 'Natural Gray'],
            '8b9c90' => ['s' => 38, 't' => 'Mantle'],
            '8ba690' => ['s' => 38, 't' => 'Envy'],
            '8ba9a5' => ['s' => 38, 't' => 'Cascade'],
            '8d8974' => ['s' => 38, 't' => 'Granite Green'],
            '8d90a1' => ['s' => 38, 't' => 'Manatee'],
            '8e8190' => ['s' => 38, 't' => 'Mamba'],
            '8f8176' => ['s' => 38, 't' => 'Squirrel'],
            '96a8a1' => ['s' => 38, 't' => 'Pewter'],
            '96bbab' => ['s' => 38, 't' => 'Summer Green'],
            '98777b' => ['s' => 38, 't' => 'Bazaar'],
            '988d77' => ['s' => 38, 't' => 'Pale Oyster'],
            '997a8d' => ['s' => 38, 't' => 'Mountbatten Pink'],
            '9999cc' => ['s' => 38, 't' => 'Blue Bell'],
            '9a9577' => ['s' => 38, 't' => 'Gurkha'],
            '9b9e8f' => ['s' => 38, 't' => 'Lemon Grass'],
            '9dacb7' => ['s' => 38, 't' => 'Gull Gray'],
            '9ea587' => ['s' => 38, 't' => 'Sage'],
            '9f9f9c' => ['s' => 38, 't' => 'Star Dust'],
            '9fa0b1' => ['s' => 38, 't' => 'Santas Gray'],
            'a1adb5' => ['s' => 38, 't' => 'Hit Gray'],
            'a2aab3' => ['s' => 38, 't' => 'Gray Chateau'],
            'a2aeab' => ['s' => 38, 't' => 'Edward'],
            'a4a49d' => ['s' => 38, 't' => 'Delta'],
            'a59b91' => ['s' => 38, 't' => 'Zorba'],
            'a6a29a' => ['s' => 38, 't' => 'Dawn'],
            'a8989b' => ['s' => 38, 't' => 'Dusty Gray'],
            'a8a589' => ['s' => 38, 't' => 'Tallow'],
            'a8ae9c' => ['s' => 38, 't' => 'Bud'],
            'a8af8e' => ['s' => 38, 't' => 'Locust'],
            'a8bd9f' => ['s' => 38, 't' => 'Norway'],
            'a9a491' => ['s' => 38, 't' => 'Gray Olive'],
            'a9b497' => ['s' => 38, 't' => 'Schist'],
            'aaa5a9' => ['s' => 38, 't' => 'Shady Lady'],
            'aba196' => ['s' => 38, 't' => 'Bronco'],
            'aca494' => ['s' => 38, 't' => 'Napa'],
            'aca586' => ['s' => 38, 't' => 'Hillary'],
            'aca59f' => ['s' => 38, 't' => 'Cloudy'],
            'acacac' => ['s' => 38, 't' => 'Silver Chalice'],
            'acb78e' => ['s' => 38, 't' => 'Swamp Green'],
            'afa09e' => ['s' => 38, 't' => 'Martini'],
            'b09a95' => ['s' => 38, 't' => 'Del Rio'],
            'b3af95' => ['s' => 38, 't' => 'Taupe Gray'],
            'b69d98' => ['s' => 38, 't' => 'Thatch'],
            'b6b095' => ['s' => 38, 't' => 'Heathered Gray'],
            '163531' => ['s' => 36, 't' => 'Gable Green'],
            '193751' => ['s' => 36, 't' => 'Nile Blue'],
            '204852' => ['s' => 36, 't' => 'Blue Dianne'],
            '262335' => ['s' => 36, 't' => 'Steel Gray'],
            '292130' => ['s' => 36, 't' => 'Bastille'],
            '292937' => ['s' => 36, 't' => 'Charade'],
            '314459' => ['s' => 36, 't' => 'Pickled Bluewood'],
            '323232' => ['s' => 36, 't' => 'Mine Shaft'],
            '353542' => ['s' => 36, 't' => 'Tuna'],
            '363050' => ['s' => 36, 't' => 'Martinique'],
            '363534' => ['s' => 36, 't' => 'Tuatara'],
            '383533' => ['s' => 36, 't' => 'Dune'],
            '384555' => ['s' => 36, 't' => 'Oxford Blue'],
            '394851' => ['s' => 36, 't' => 'Limed Spruce'],
            '405169' => ['s' => 36, 't' => 'Fiord'],
            '414257' => ['s' => 36, 't' => 'Gun Powder'],
            '423921' => ['s' => 36, 't' => 'Lisbon Brown'],
            '444954' => ['s' => 36, 't' => 'Mako'],
            '454936' => ['s' => 36, 't' => 'Kelp'],
            '465945' => ['s' => 36, 't' => 'Gray Asparagus'],
            '483131' => ['s' => 36, 't' => 'Woody Brown'],
            '504351' => ['s' => 36, 't' => 'Mortar'],
            '514649' => ['s' => 36, 't' => 'Emperor'],
            '533455' => ['s' => 36, 't' => 'Voodoo'],
            '544333' => ['s' => 36, 't' => 'Judge Gray'],
            '593737' => ['s' => 36, 't' => 'Congo Brown'],
            '594433' => ['s' => 36, 't' => 'Millbrook'],
            '614051' => ['s' => 36, 't' => 'Eggplant'],
            '692545' => ['s' => 36, 't' => 'Tawny Port'],
            '063537' => ['s' => 36, 't' => 'Tiber'],
            '0e2a30' => ['s' => 36, 't' => 'Firefly'],
            '151f4c' => ['s' => 36, 't' => 'Bunting'],
            '162a40' => ['s' => 36, 't' => 'Big Stone'],
            '16322c' => ['s' => 36, 't' => 'Timber Green'],
            '1c402e' => ['s' => 36, 't' => 'Everglade'],
            '1e433c' => ['s' => 36, 't' => 'Te Papa Green'],
            '202e54' => ['s' => 36, 't' => 'Cloud Burst'],
            '251f4f' => ['s' => 36, 't' => 'Port Gore'],
            '26283b' => ['s' => 36, 't' => 'Ebony Clay'],
            '27504b' => ['s' => 36, 't' => 'Plantation'],
            '2a2630' => ['s' => 36, 't' => 'Baltic Sea'],
            '2b3228' => ['s' => 36, 't' => 'Heavy Metal'],
            '2c2133' => ['s' => 36, 't' => 'Bleached Cedar'],
            '2d383a' => ['s' => 36, 't' => 'Outer Space'],
            '2e3f62' => ['s' => 36, 't' => 'Rhino'],
            '2f5a57' => ['s' => 36, 't' => 'Spectra'],
            '2f6168' => ['s' => 36, 't' => 'Casal'],
            '304b6a' => ['s' => 36, 't' => 'San Juan'],
            '32293a' => ['s' => 36, 't' => 'Blackcurrant'],
            '325d52' => ['s' => 36, 't' => 'Stromboli'],
            '33292f' => ['s' => 36, 't' => 'Thunder'],
            '3a6a47' => ['s' => 36, 't' => 'Killarney'],
            '3c4151' => ['s' => 36, 't' => 'Bright Gray'],
            '3c4443' => ['s' => 36, 't' => 'Cape Cod'],
            '3c493a' => ['s' => 36, 't' => 'Lunar Green'],
            '3e3a44' => ['s' => 36, 't' => 'Ship Gray'],
            '3f4c3a' => ['s' => 36, 't' => 'Cabbage Pont'],
            '3f583b' => ['s' => 36, 't' => 'Tom Thumb'],
            '3f5d53' => ['s' => 36, 't' => 'Mineral Green'],
            '403b38' => ['s' => 36, 't' => 'Masala'],
            '413c37' => ['s' => 36, 't' => 'Merlin'],
            '433e37' => ['s' => 36, 't' => 'Armadillo'],
            '434c59' => ['s' => 36, 't' => 'River Bed'],
            '483c32' => ['s' => 36, 't' => 'Taupe'],
            '4a3c30' => ['s' => 36, 't' => 'Mondo'],
            '4a4244' => ['s' => 36, 't' => 'Tundora'],
            '4a444b' => ['s' => 36, 't' => 'Gravel'],
            '4a4e5a' => ['s' => 36, 't' => 'Trout'],
            '4b5d52' => ['s' => 36, 't' => 'Nandor'],
            '4c3024' => ['s' => 36, 't' => 'Saddle'],
            '4c4f56' => ['s' => 36, 't' => 'Abbey'],
            '4d282d' => ['s' => 36, 't' => 'Cowboy'],
            '4d282e' => ['s' => 36, 't' => 'Livid Brown'],
            '4d3833' => ['s' => 36, 't' => 'Rock'],
            '4d5328' => ['s' => 36, 't' => 'Woodland'],
            '4e2a5a' => ['s' => 36, 't' => 'Bossanova'],
            '4e3b41' => ['s' => 36, 't' => 'Matterhorn'],
            '4e4562' => ['s' => 36, 't' => 'Mulled Wine'],
            '4e6649' => ['s' => 36, 't' => 'Axolotl'],
            '516e3d' => ['s' => 36, 't' => 'Chalet Green'],
            '54534d' => ['s' => 36, 't' => 'Fuscous Gray'],
            '591d35' => ['s' => 36, 't' => 'Wine Berry'],
            '5d4c51' => ['s' => 36, 't' => 'Don Juan'],
            '5d5e37' => ['s' => 36, 't' => 'Verdigris'],
            '5e483e' => ['s' => 36, 't' => 'Kabul'],
            '5e5d3b' => ['s' => 36, 't' => 'Hemlock'],
            '615d30' => ['s' => 36, 't' => 'Costa Del Sol'],
            '692d54' => ['s' => 36, 't' => 'Finn'],
            '507672' => ['s' => 37, 't' => 'Cutty Sark'],
            '534491' => ['s' => 37, 't' => 'Victoria'],
            '585562' => ['s' => 37, 't' => 'Scarpa Flow'],
            '626649' => ['s' => 37, 't' => 'Finch'],
            '646077' => ['s' => 37, 't' => 'Dolphin'],
            '646463' => ['s' => 37, 't' => 'Storm Dust'],
            '676662' => ['s' => 37, 't' => 'Ironside Gray'],
            '678975' => ['s' => 37, 't' => 'Viridian Green'],
            '685558' => ['s' => 37, 't' => 'Zambezi'],
            '706555' => ['s' => 37, 't' => 'Coffee'],
            '714693' => ['s' => 37, 't' => 'Affair'],
            '716338' => ['s' => 37, 't' => 'Yellow Metal'],
            '717486' => ['s' => 37, 't' => 'Storm Gray'],
            '718080' => ['s' => 37, 't' => 'Sirocco'],
            '738678' => ['s' => 37, 't' => 'Xanadu'],
            '796878' => ['s' => 37, 't' => 'Old Lavender'],
            '796989' => ['s' => 37, 't' => 'Rum'],
            '817377' => ['s' => 37, 't' => 'Empress'],
            '858470' => ['s' => 37, 't' => 'Bandicoot'],
            '893456' => ['s' => 37, 't' => 'Camelot'],
            '894367' => ['s' => 37, 't' => 'Cannon Pink'],
            '956387' => ['s' => 37, 't' => 'Strikemaster'],
            '2c8c84' => ['s' => 37, 't' => 'Lochinvar'],
            '317d82' => ['s' => 37, 't' => 'Paradiso'],
            '36747d' => ['s' => 37, 't' => 'Ming'],
            '3a686c' => ['s' => 37, 't' => 'William'],
            '3b7a57' => ['s' => 37, 't' => 'Amazon'],
            '3d7d52' => ['s' => 37, 't' => 'Goblin'],
            '40826d' => ['s' => 37, 't' => 'Viridian'],
            '414c7d' => ['s' => 37, 't' => 'East Bay'],
            '41aa78' => ['s' => 37, 't' => 'Ocean Green'],
            '4e7f9e' => ['s' => 37, 't' => 'Wedgewood'],
            '4f7942' => ['s' => 37, 't' => 'Fern Green'],
            '4f9d5d' => ['s' => 37, 't' => 'Fruit Salad'],
            '517c66' => ['s' => 37, 't' => 'Como'],
            '51808f' => ['s' => 37, 't' => 'Smalt Blue'],
            '523c94' => ['s' => 37, 't' => 'Gigas'],
            '53824b' => ['s' => 37, 't' => 'Hippie Green'],
            '556d56' => ['s' => 37, 't' => 'Finlandia'],
            '5a6e9c' => ['s' => 37, 't' => 'Waikawa Gray'],
            '5c5d75' => ['s' => 37, 't' => 'Comet'],
            '5d5c58' => ['s' => 37, 't' => 'Chicago'],
            '5d7747' => ['s' => 37, 't' => 'Dingley'],
            '5f5f6e' => ['s' => 37, 't' => 'Mid Gray'],
            '5f6672' => ['s' => 37, 't' => 'Shuttle Gray'],
            '605b73' => ['s' => 37, 't' => 'Smoky'],
            '606e68' => ['s' => 37, 't' => 'Corduroy'],
            '61845f' => ['s' => 37, 't' => 'Glade Green'],
            '624e9a' => ['s' => 37, 't' => 'Butterfly Bush'],
            '6456b7' => ['s' => 37, 't' => 'Blue Violet'],
            '646a54' => ['s' => 37, 't' => 'Siam'],
            '646e75' => ['s' => 37, 't' => 'Nevada'],
            '65745d' => ['s' => 37, 't' => 'Willow Grove'],
            '675fa6' => ['s' => 37, 't' => 'Scampi'],
            '685e6e' => ['s' => 37, 't' => 'Salt Box'],
            '695f62' => ['s' => 37, 't' => 'Scorpion'],
            '6a6051' => ['s' => 37, 't' => 'Soya Bean'],
            '6b3fa0' => ['s' => 37, 't' => 'Royal Purple'],
            '6b5755' => ['s' => 37, 't' => 'Dorado'],
            '6c3082' => ['s' => 37, 't' => 'Eminence'],
            '6d5e54' => ['s' => 37, 't' => 'Pine Cone'],
            '6d6c6c' => ['s' => 37, 't' => 'Dove Gray'],
            '6e6d57' => ['s' => 37, 't' => 'Kokoda'],
            '6e7783' => ['s' => 37, 't' => 'Pale Sky'],
            '6f6a61' => ['s' => 37, 't' => 'Flint'],
            '6f8e63' => ['s' => 37, 't' => 'Highland'],
            '704f50' => ['s' => 37, 't' => 'Ferra'],
            '715d47' => ['s' => 37, 't' => 'Tobacco Brown'],
            '716b56' => ['s' => 37, 't' => 'Peat'],
            '726d4e' => ['s' => 37, 't' => 'Go Ben'],
            '727b89' => ['s' => 37, 't' => 'Raven'],
            '736d58' => ['s' => 37, 't' => 'Crocodile'],
            '747d63' => ['s' => 37, 't' => 'Limed Ash'],
            '747d83' => ['s' => 37, 't' => 'Rolling Stone'],
            '755a57' => ['s' => 37, 't' => 'Russett'],
            '76395d' => ['s' => 37, 't' => 'Cosmic'],
            '776f61' => ['s' => 37, 't' => 'Pablo'],
            '78866b' => ['s' => 37, 't' => 'Camouflage Green'],
            '795d4c' => ['s' => 37, 't' => 'Roman Coffee'],
            '796a78' => ['s' => 37, 't' => 'Fedora'],
            '796d62' => ['s' => 37, 't' => 'Sandstone'],
            '7a7a7a' => ['s' => 37, 't' => 'Boulder'],
            '7b7874' => ['s' => 37, 't' => 'Tapa'],
            '7b8265' => ['s' => 37, 't' => 'Flax Smoke'],
            '7c778a' => ['s' => 37, 't' => 'Topaz'],
            '7c7b7a' => ['s' => 37, 't' => 'Concord'],
            '7c7b82' => ['s' => 37, 't' => 'Jumbo'],
            '7f626d' => ['s' => 37, 't' => 'Falcon'],
            '7f7589' => ['s' => 37, 't' => 'Mobster'],
            '807e79' => ['s' => 37, 't' => 'Friar Gray'],
            '816e71' => ['s' => 37, 't' => 'Spicy Pink'],
            '826f65' => ['s' => 37, 't' => 'Sand Dune'],
            '87756e' => ['s' => 37, 't' => 'Americano'],
            '877c7b' => ['s' => 37, 't' => 'Hurricane'],
            '897d6d' => ['s' => 37, 't' => 'Makara'],
            '8e6f70' => ['s' => 37, 't' => 'Opium'],
            '9ac2b8' => ['s' => 39, 't' => 'Shadow Green'],
            '9eb1cd' => ['s' => 39, 't' => 'Rock Blue'],
            '9fd7d3' => ['s' => 39, 't' => 'Sinbad'],
            'a1dad7' => ['s' => 39, 't' => 'Aqua Island'],
            'a4a6d3' => ['s' => 39, 't' => 'Wistful'],
            'a8e3bd' => ['s' => 39, 't' => 'Chinook'],
            'a9acb6' => ['s' => 39, 't' => 'Aluminium'],
            'a9b2c3' => ['s' => 39, 't' => 'Cadet Blue'],
            'a9bdbf' => ['s' => 39, 't' => 'Tower Gray'],
            'a9bef2' => ['s' => 39, 't' => 'Perano'],
            'a9c6c2' => ['s' => 39, 't' => 'Opal'],
            'aaa9cd' => ['s' => 39, 't' => 'Logan'],
            'aaabb7' => ['s' => 39, 't' => 'Spun Pearl'],
            'aba0d9' => ['s' => 39, 't' => 'Cold Purple'],
            'ac91ce' => ['s' => 39, 't' => 'East Side'],
            'accbb1' => ['s' => 39, 't' => 'Spring Rain'],
            'ace1af' => ['s' => 39, 't' => 'Celadon'],
            'adbed1' => ['s' => 39, 't' => 'Casper'],
            'addfad' => ['s' => 39, 't' => 'Moss Green'],
            'ade6c4' => ['s' => 39, 't' => 'Padua'],
            'afb1b8' => ['s' => 39, 't' => 'Bombay'],
            'afbdd9' => ['s' => 39, 't' => 'Pigeon Post'],
            'b1e2c1' => ['s' => 39, 't' => 'Fringy Flower'],
            'b4cfd3' => ['s' => 39, 't' => 'Jungle Mist'],
            'b5d2ce' => ['s' => 39, 't' => 'Jet Stream'],
            'b6baa4' => ['s' => 39, 't' => 'Eagle'],
            'b6d1ea' => ['s' => 39, 't' => 'Spindle'],
            'b6d3bf' => ['s' => 39, 't' => 'Gum Leaf'],
            'b7b1b1' => ['s' => 39, 't' => 'Nobel'],
            'b7c3d0' => ['s' => 39, 't' => 'Heather'],
            'b7f0be' => ['s' => 39, 't' => 'Madang'],
            'b8c1b1' => ['s' => 39, 't' => 'Green Spring'],
            'b9c8ac' => ['s' => 39, 't' => 'Rainee'],
            'bab1a2' => ['s' => 39, 't' => 'Nomad'],
            'bac7c9' => ['s' => 39, 't' => 'Submarine'],
            'bbd7c1' => ['s' => 39, 't' => 'Surf'],
            'bcc9c2' => ['s' => 39, 't' => 'Powder Ash'],
            'bdb1a8' => ['s' => 39, 't' => 'Silk'],
            'bdb2a1' => ['s' => 39, 't' => 'Malta'],
            'bdb3c7' => ['s' => 39, 't' => 'Chatelle'],
            'bdbbd7' => ['s' => 39, 't' => 'Lavender Gray'],
            'bdbdc6' => ['s' => 39, 't' => 'French Gray'],
            'bdc8b3' => ['s' => 39, 't' => 'Clay Ash'],
            'bdc9ce' => ['s' => 39, 't' => 'Loblolly'],
            'bea6c3' => ['s' => 39, 't' => 'London Hue'],
            'beb5b7' => ['s' => 39, 't' => 'Pink Swan'],
            'bfb8b0' => ['s' => 39, 't' => 'Tide'],
            'bfbed8' => ['s' => 39, 't' => 'Blue Haze'],
            'bfc1c2' => ['s' => 39, 't' => 'Silver Sand'],
            'bfdbe2' => ['s' => 39, 't' => 'Ziggurat'],
            'c0c0c0' => ['s' => 39, 't' => 'Silver'],
            'c0d3b9' => ['s' => 39, 't' => 'Pale Leaf'],
            'c0d8b6' => ['s' => 39, 't' => 'Pixie Green'],
            'c1b7a4' => ['s' => 39, 't' => 'Bison Hide'],
            'c1bab0' => ['s' => 39, 't' => 'Tea'],
            'c1becd' => ['s' => 39, 't' => 'Gray Suit'],
            'c1d7b0' => ['s' => 39, 't' => 'Sprout'],
            'c2bdb6' => ['s' => 39, 't' => 'Cotton Seed'],
            'c2cac4' => ['s' => 39, 't' => 'Pumice'],
            'c3bfc1' => ['s' => 39, 't' => 'Pale Slate'],
            'c3c3bd' => ['s' => 39, 't' => 'Gray Nickel'],
            'c3cde6' => ['s' => 39, 't' => 'Periwinkle Gray'],
            'c3d1d1' => ['s' => 39, 't' => 'Tiara'],
            'c4c4bc' => ['s' => 39, 't' => 'Mist Gray'],
            'c4d0b0' => ['s' => 39, 't' => 'Coriander'],
            'c5dbca' => ['s' => 39, 't' => 'Sea Mist'],
            'c6c3b5' => ['s' => 39, 't' => 'Ash'],
            'c6c8bd' => ['s' => 39, 't' => 'Kangaroo'],
            'c7bca2' => ['s' => 39, 't' => 'Coral Reef'],
            'c7c4bf' => ['s' => 39, 't' => 'Cloud'],
            'c7c9d5' => ['s' => 39, 't' => 'Ghost'],
            'c8a2c8' => ['s' => 39, 't' => 'Lilac'],
            'c8aabf' => ['s' => 39, 't' => 'Lily'],
            'c8e3d7' => ['s' => 39, 't' => 'Edgewater'],
            'c9c0bb' => ['s' => 39, 't' => 'Silver Rust'],
            'c9d9d2' => ['s' => 39, 't' => 'Conch'],
            'cadcd4' => ['s' => 39, 't' => 'Paris White'],
            'cbcab6' => ['s' => 39, 't' => 'Foggy Gray'],
            'cbd3b0' => ['s' => 39, 't' => 'Green Mist'],
            'cbdbd6' => ['s' => 39, 't' => 'Nebula'],
            'cccaa8' => ['s' => 39, 't' => 'Thistle Green'],
            'cebaba' => ['s' => 39, 't' => 'Cold Turkey'],
            'cec7a7' => ['s' => 39, 't' => 'Chino'],
            'cfdccf' => ['s' => 39, 't' => 'Tasman'],
            'd0c0e5' => ['s' => 39, 't' => 'Prelude'],
            'd0f0c0' => ['s' => 39, 't' => 'Tea Green'],
            'd1bea8' => ['s' => 39, 't' => 'Vanilla'],
            'd1c6b4' => ['s' => 39, 't' => 'Soft Amber'],
            'd1d2ca' => ['s' => 39, 't' => 'Celeste'],
            'd1d2dd' => ['s' => 39, 't' => 'Mischka'],
            'd3cbba' => ['s' => 39, 't' => 'Sisal'],
            'd3cdc5' => ['s' => 39, 't' => 'Swirl'],
            'd4b6af' => ['s' => 39, 't' => 'Clam Shell'],
            'd4c4a8' => ['s' => 39, 't' => 'Akaroa'],
            'd6d6d1' => ['s' => 39, 't' => 'Quill Gray'],
            'd8bfd8' => ['s' => 39, 't' => 'Thistle'],
            'd8c2d5' => ['s' => 39, 't' => 'Maverick'],
            'd9d6cf' => ['s' => 39, 't' => 'Timberwolf'],
            'd9dcc1' => ['s' => 39, 't' => 'Tana'],
            'dcb4bc' => ['s' => 39, 't' => 'Blossom'],
            'decbc6' => ['s' => 39, 't' => 'Wafer'],
            'e1c0c8' => ['s' => 39, 't' => 'Pink Flare'],
            'e3bebe' => ['s' => 39, 't' => 'Cavern Pink'],
            'e4c2d5' => ['s' => 39, 't' => 'Melanie'],
            'e4d1c0' => ['s' => 39, 't' => 'Bone'],
            'e4d5b7' => ['s' => 39, 't' => 'Grain Brown'],
            'e5ccc9' => ['s' => 39, 't' => 'Dust Storm'],
            'e5d7bd' => ['s' => 39, 't' => 'Stark White'],
            'e6d7b9' => ['s' => 39, 't' => 'Double Spanish White'],
            'e7bcb4' => ['s' => 39, 't' => 'Rose Fog'],
            'c7dde5' => ['s' => 40, 't' => 'Botticelli'],
            'cae6da' => ['s' => 40, 't' => 'Skeptic'],
            'cfe5d2' => ['s' => 40, 't' => 'Surf Crest'],
            'd2f6de' => ['s' => 40, 't' => 'Blue Romance'],
            'd4d7d9' => ['s' => 40, 't' => 'Iron'],
            'd4dfe2' => ['s' => 40, 't' => 'Geyser'],
            'd4e2fc' => ['s' => 40, 't' => 'Hawkes Blue'],
            'd5f6e3' => ['s' => 40, 't' => 'Granny Apple'],
            'd6ffdb' => ['s' => 40, 't' => 'Snowy Mint'],
            'd8fcfa' => ['s' => 40, 't' => 'Foam'],
            'd9e4f5' => ['s' => 40, 't' => 'Link Water'],
            'd9f7ff' => ['s' => 40, 't' => 'Mabel'],
            'daecd6' => ['s' => 40, 't' => 'Zanah'],
            'daf4f0' => ['s' => 40, 't' => 'Iceberg'],
            'dbdbdb' => ['s' => 40, 't' => 'Alto'],
            'dbfff8' => ['s' => 40, 't' => 'Frosted Mint'],
            'dcd9d2' => ['s' => 40, 't' => 'Westar'],
            'dcddcc' => ['s' => 40, 't' => 'Moon Mist'],
            'dcf0ea' => ['s' => 40, 't' => 'Swans Down'],
            'ddd6d5' => ['s' => 40, 't' => 'Swiss Coffee'],
            'ddf9f1' => ['s' => 40, 't' => 'White Ice'],
            'dee5c0' => ['s' => 40, 't' => 'Beryl Green'],
            'def5ff' => ['s' => 40, 't' => 'Pattens Blue'],
            'dfcfdb' => ['s' => 40, 't' => 'Lola'],
            'dfecda' => ['s' => 40, 't' => 'Willow Brook'],
            'e1e6d6' => ['s' => 40, 't' => 'Periglacial Blue'],
            'e1ead4' => ['s' => 40, 't' => 'Kidnapper'],
            'e1f6e8' => ['s' => 40, 't' => 'Tara'],
            'e2d8ed' => ['s' => 40, 't' => 'Snuff'],
            'e2ebed' => ['s' => 40, 't' => 'Mystic'],
            'e2f3ec' => ['s' => 40, 't' => 'Apple Green'],
            'e3f5e1' => ['s' => 40, 't' => 'Peppermint'],
            'e4cfde' => ['s' => 40, 't' => 'Twilight'],
            'e4f6e7' => ['s' => 40, 't' => 'Frostee'],
            'e4ffd1' => ['s' => 40, 't' => 'Snow Flurry'],
            'e5e0e1' => ['s' => 40, 't' => 'Bon Jour'],
            'e5e5e5' => ['s' => 40, 't' => 'Mercury'],
            'e6e4d4' => ['s' => 40, 't' => 'Satin Linen'],
            'e6f2ea' => ['s' => 40, 't' => 'Harp'],
            'e6f8f3' => ['s' => 40, 't' => 'Off Green'],
            'e6ffe9' => ['s' => 40, 't' => 'Hint of Green'],
            'e7ece6' => ['s' => 40, 't' => 'Gray Nurse'],
            'e8e0d5' => ['s' => 40, 't' => 'Pearl Bush'],
            'e8ebe0' => ['s' => 40, 't' => 'Green White'],
            'e8f1d4' => ['s' => 40, 't' => 'Chrome White'],
            'e8f2eb' => ['s' => 40, 't' => 'Gin'],
            'e8f5f2' => ['s' => 40, 't' => 'Aqua Squeeze'],
            'e9e3e3' => ['s' => 40, 't' => 'Ebb'],
            'e9f8ed' => ['s' => 40, 't' => 'Ottoman'],
            'eae8d4' => ['s' => 40, 't' => 'White Rock'],
            'eaf6ee' => ['s' => 40, 't' => 'Panache'],
            'ecebce' => ['s' => 40, 't' => 'Aths Special'],
            'edf5dd' => ['s' => 40, 't' => 'Frost'],
            'eededa' => ['s' => 40, 't' => 'Bizarre'],
            'eeeee8' => ['s' => 40, 't' => 'Cararra'],
            'eef0f3' => ['s' => 40, 't' => 'Athens Gray'],
            'eef4de' => ['s' => 40, 't' => 'Loafer'],
            'eeffe2' => ['s' => 40, 't' => 'Rice Flower'],
            'efefef' => ['s' => 40, 't' => 'Gallery'],
            'f0e2ec' => ['s' => 40, 't' => 'Prim'],
            'f1e9d2' => ['s' => 40, 't' => 'Parchment'],
            'f1f1f1' => ['s' => 40, 't' => 'Seashell'],
            'f3e9e5' => ['s' => 40, 't' => 'Dawn Pink'],
            'f3edcf' => ['s' => 40, 't' => 'Wheatfield'],
            'f3fbd4' => ['s' => 40, 't' => 'Orinoco'],
            'f3ffd8' => ['s' => 40, 't' => 'Carla'],
            'f4ebd3' => ['s' => 40, 't' => 'Janna'],
            'f4f2ee' => ['s' => 40, 't' => 'Pampas'],
            'f5e7e2' => ['s' => 40, 't' => 'Pot Pourri'],
            'f5edef' => ['s' => 40, 't' => 'Soft Peach'],
            'f5f3e5' => ['s' => 40, 't' => 'Ecru White'],
            'f5f5dc' => ['s' => 40, 't' => 'Beige'],
            'f6f0e6' => ['s' => 40, 't' => 'Merino'],
            'f6ffdc' => ['s' => 40, 't' => 'Spring Sun'],
            'f7f2e1' => ['s' => 40, 't' => 'Quarter Spanish White'],
            'f8f0e8' => ['s' => 40, 't' => 'White Linen'],
            'f8f7dc' => ['s' => 40, 't' => 'Coconut Cream'],
            'f9e0ed' => ['s' => 40, 't' => 'Carousel Pink'],
            'faf0e6' => ['s' => 40, 't' => 'Linen'],
            'faf7d6' => ['s' => 40, 't' => 'Citrine White'],
            'fcf4dc' => ['s' => 40, 't' => 'Pearl Lusta'],
            'fcfeda' => ['s' => 40, 't' => 'Moon Glow'],
            'fef7de' => ['s' => 40, 't' => 'Half Dutch White'],
            'fff6df' => ['s' => 40, 't' => 'Varden'],
            '220878' => ['s' => 11, 't' => 'Deep Blue'],
            '260368' => ['s' => 11, 't' => 'Paua'],
            '350036' => ['s' => 11, 't' => 'Mardi Gras'],
            '380474' => ['s' => 11, 't' => 'Blue Diamond'],
            '410056' => ['s' => 11, 't' => 'Ripe Plum'],
            '431560' => ['s' => 11, 't' => 'Scarlet Gum'],
            '480656' => ['s' => 11, 't' => 'Clairvoyant'],
            '660045' => ['s' => 11, 't' => 'Pompadour'],
            '871550' => ['s' => 11, 't' => 'Disco'],
            '110c6c' => ['s' => 11, 't' => 'Arapawa'],
            '1a1a68' => ['s' => 11, 't' => 'Lucky Point'],
            '1b0245' => ['s' => 11, 't' => 'Tolopea'],
            '1b127b' => ['s' => 11, 't' => 'Deep Koamaru'],
            '240a40' => ['s' => 11, 't' => 'Violet'],
            '26056a' => ['s' => 11, 't' => 'Paris M'],
            '290c5e' => ['s' => 11, 't' => 'Violent Violet'],
            '2a0359' => ['s' => 11, 't' => 'Cherry Pie'],
            '2b194f' => ['s' => 11, 't' => 'Valhalla'],
            '2c0e8c' => ['s' => 11, 't' => 'Blue Gem'],
            '32127a' => ['s' => 11, 't' => 'Persian Indigo'],
            '33036b' => ['s' => 11, 't' => 'Christalle'],
            '350e42' => ['s' => 11, 't' => 'Valentino'],
            '350e57' => ['s' => 11, 't' => 'Jagger'],
            '381a51' => ['s' => 11, 't' => 'Grape'],
            '3a2a6a' => ['s' => 11, 't' => 'Jacarta'],
            '3c0878' => ['s' => 11, 't' => 'Windsor'],
            '3c1f76' => ['s' => 11, 't' => 'Meteorite'],
            '3e0480' => ['s' => 11, 't' => 'Kingfisher Daisy'],
            '3f307f' => ['s' => 11, 't' => 'Minsk'],
            '460b41' => ['s' => 11, 't' => 'Loulou'],
            '4b0082' => ['s' => 11, 't' => 'Pigment Indigo'],
            '4d0135' => ['s' => 11, 't' => 'Blackberry'],
            '4f1c70' => ['s' => 11, 't' => 'Honey Flower'],
            '4f2398' => ['s' => 11, 't' => 'Daisy Bush'],
            '5c0536' => ['s' => 11, 't' => 'Mulberry Wood'],
            '66023c' => ['s' => 11, 't' => 'Tyrian Purple'],
            '736c9f' => ['s' => 11, 't' => 'Kimberly'],
            '800b47' => ['s' => 11, 't' => 'Rose Bud Cherry'],
            '8c055e' => ['s' => 11, 't' => 'Cardinal Pink'],
            '660099' => ['s' => 12, 't' => 'Purple'],
            '803790' => ['s' => 12, 't' => 'Vivid Violet'],
            '843179' => ['s' => 12, 't' => 'Plum'],
            '991199' => ['s' => 12, 't' => 'Violet Eggplant'],
            '652dc1' => ['s' => 12, 't' => 'Purple Heart'],
            '714ab2' => ['s' => 12, 't' => 'Studio'],
            '731e8f' => ['s' => 12, 't' => 'Seance'],
            '7563a8' => ['s' => 12, 't' => 'Deluge'],
            '7666c6' => ['s' => 12, 't' => 'Blue Marguerite'],
            '7a58c1' => ['s' => 12, 't' => 'Fuchsia Blue'],
            '7f76d3' => ['s' => 12, 't' => 'Moody Blue'],
            '8a73d6' => ['s' => 12, 't' => 'True V'],
            '8b00ff' => ['s' => 12, 't' => 'Electric Violet'],
            '8c6495' => ['s' => 12, 't' => 'Trendy Pink'],
            '9370db' => ['s' => 13, 't' => 'Medium Purple'],
            '9678b6' => ['s' => 13, 't' => 'Purple Mountain\'s Majesty'],
            '967bb6' => ['s' => 13, 't' => 'Lavender Purple'],
            '9771b5' => ['s' => 13, 't' => 'Wisteria'],
            '9874d3' => ['s' => 13, 't' => 'Lilac Bush'],
            '9966cc' => ['s' => 13, 't' => 'Amethyst'],
            'ae809e' => ['s' => 13, 't' => 'Bouquet'],
            'c154c1' => ['s' => 13, 't' => 'Fuchsia Pink'],
            'ff00ff' => ['s' => 13, 't' => 'Magenta / Fuchsia'],
            'a397b4' => ['s' => 14, 't' => 'Amethyst Smoke'],
            'a899e6' => ['s' => 14, 't' => 'Dull Lavender'],
            'b2a1ea' => ['s' => 14, 't' => 'Biloba Flower'],
            'b57edc' => ['s' => 14, 't' => 'Lavender'],
            'c9a0dc' => ['s' => 14, 't' => 'Light Wisteria'],
            'da70d6' => ['s' => 14, 't' => 'Orchid'],
            'df73ff' => ['s' => 14, 't' => 'Heliotrope'],
            'ee82ee' => ['s' => 14, 't' => 'Lavender Magenta'],
            'ff66ff' => ['s' => 14, 't' => 'Pink Flamingo'],
            'ff6fff' => ['s' => 14, 't' => 'Blush Pink'],
            'c7c1ff' => ['s' => 15, 't' => 'Melrose'],
            'ccccff' => ['s' => 15, 't' => 'Periwinkle'],
            'd0bef8' => ['s' => 15, 't' => 'Perfume'],
            'd6cef6' => ['s' => 15, 't' => 'Moon Raker'],
            'd7d0ff' => ['s' => 15, 't' => 'Fog'],
            'e0b0ff' => ['s' => 15, 't' => 'Mauve'],
            'ecc7ee' => ['s' => 15, 't' => 'French Lilac'],
            '661010' => ['s' => 6, 't' => 'Dark Tan'],
            '780109' => ['s' => 6, 't' => 'Japanese Maple'],
            '800000' => ['s' => 6, 't' => 'Maroon'],
            '801818' => ['s' => 6, 't' => 'Falu Red'],
            '831923' => ['s' => 6, 't' => 'Merlot'],
            '860111' => ['s' => 6, 't' => 'Red Devil'],
            '900020' => ['s' => 6, 't' => 'Burgundy'],
            '52001f' => ['s' => 6, 't' => 'Castro'],
            '5c0120' => ['s' => 6, 't' => 'Bordeaux'],
            '65000b' => ['s' => 6, 't' => 'Rosewood'],
            '651a14' => ['s' => 6, 't' => 'Cherrywood'],
            '67032d' => ['s' => 6, 't' => 'Black Rose'],
            '6d0101' => ['s' => 6, 't' => 'Lonestar'],
            '6e0902' => ['s' => 6, 't' => 'Red Oxide'],
            '711a00' => ['s' => 6, 't' => 'Cedar Wood Finish'],
            '72010f' => ['s' => 6, 't' => 'Venetian Red'],
            '770f05' => ['s' => 6, 't' => 'Dark Burgundy'],
            '7a013a' => ['s' => 6, 't' => 'Siren'],
            '7c1c05' => ['s' => 6, 't' => 'Kenyan Copper'],
            '8b0723' => ['s' => 6, 't' => 'Monarch'],
            '8d0226' => ['s' => 6, 't' => 'Paprika'],
            '8e0000' => ['s' => 6, 't' => 'Red Berry'],
            '8f021c' => ['s' => 6, 't' => 'Pohutukawa'],
            '92000a' => ['s' => 6, 't' => 'Sangria'],
            '950015' => ['s' => 7, 't' => 'Scarlett'],
            '960018' => ['s' => 7, 't' => 'Carmine'],
            '991613' => ['s' => 7, 't' => 'Tamarillo'],
            '991b07' => ['s' => 7, 't' => 'Totem Pole'],
            'a72525' => ['s' => 7, 't' => 'Mexican Red'],
            'b10000' => ['s' => 7, 't' => 'Bright Red'],
            'b20931' => ['s' => 7, 't' => 'Shiraz'],
            'b32d29' => ['s' => 7, 't' => 'Tall Poppy'],
            'b81104' => ['s' => 7, 't' => 'Milano Red'],
            'ba0101' => ['s' => 7, 't' => 'Guardsman Red'],
            'c02b18' => ['s' => 7, 't' => 'Thunderbird'],
            'c41e3a' => ['s' => 7, 't' => 'Cardinal'],
            'c7031e' => ['s' => 7, 't' => 'Monza'],
            'a3807b' => ['s' => 10, 't' => 'Pharlap'],
            'e2725b' => ['s' => 10, 't' => 'Terracotta'],
            'e97451' => ['s' => 10, 't' => 'Burnt Sienna'],
            'eb9373' => ['s' => 10, 't' => 'Apricot'],
            'f57584' => ['s' => 10, 't' => 'Froly'],
            'fb8989' => ['s' => 10, 't' => 'Geraldine'],
            'fc80a5' => ['s' => 10, 't' => 'Tickle Me Pink'],
            'fe6f5e' => ['s' => 10, 't' => 'Bittersweet'],
            'ff6b53' => ['s' => 10, 't' => 'Persimmon'],
            'ff7f50' => ['s' => 10, 't' => 'Coral'],
            'ff8c69' => ['s' => 10, 't' => 'Salmon'],
            'ff9966' => ['s' => 10, 't' => 'Atomic Tangerine'],
            'ff9980' => ['s' => 10, 't' => 'Vivid Tangerine'],
            'ffa194' => ['s' => 10, 't' => 'Mona Lisa'],
            'ffab81' => ['s' => 10, 't' => 'Hit Pink'],
            'ca3435' => ['s' => 9, 't' => 'Flush Mahogany'],
            'cc3333' => ['s' => 9, 't' => 'Persian Red'],
            'd54600' => ['s' => 9, 't' => 'Grenadier'],
            'd84437' => ['s' => 9, 't' => 'Valencia'],
            'dc143c' => ['s' => 9, 't' => 'Crimson'],
            'dc4333' => ['s' => 9, 't' => 'Punch'],
            'e32636' => ['s' => 9, 't' => 'Alizarin Crimson'],
            'e34234' => ['s' => 9, 't' => 'Cinnabar'],
            'e64e03' => ['s' => 9, 't' => 'Trinidad'],
            'ed0a3f' => ['s' => 9, 't' => 'Red Ribbon'],
            'f2552a' => ['s' => 9, 't' => 'Flamingo'],
            'f34723' => ['s' => 9, 't' => 'Pomegranate'],
            'fd0e35' => ['s' => 9, 't' => 'Torch Red'],
            'fe4c40' => ['s' => 9, 't' => 'Sunset Orange'],
            'ff2400' => ['s' => 9, 't' => 'Scarlet'],
            'ff3f34' => ['s' => 9, 't' => 'Red Orange'],
            'ff4040' => ['s' => 9, 't' => 'Coral Red'],
            'ff4d00' => ['s' => 9, 't' => 'Vermilion'],
            'ff4f00' => ['s' => 9, 't' => 'International Orange'],
            'ff6037' => ['s' => 9, 't' => 'Outrageous Orange'],
            'ff0000' => ['s' => 8, 't' => 'Red'],
            '990066' => ['s' => 16, 't' => 'Fresh Eggplant'],
            '983d61' => ['s' => 16, 't' => 'Vin Rouge'],
            'a2006d' => ['s' => 16, 't' => 'Flirt'],
            'a23b6c' => ['s' => 16, 't' => 'Rouge'],
            'a50b5e' => ['s' => 16, 't' => 'Jazzberry Jam'],
            'aa375a' => ['s' => 16, 't' => 'Night Shadz'],
            'ab0563' => ['s' => 16, 't' => 'Lipstick'],
            'ab3472' => ['s' => 16, 't' => 'Royal Heath'],
            'ae4560' => ['s' => 16, 't' => 'Hippie Pink'],
            'b04c6a' => ['s' => 16, 't' => 'Cadillac'],
            'b05e81' => ['s' => 16, 't' => 'Tapestry'],
            'b44668' => ['s' => 16, 't' => 'Blush'],
            'b6316c' => ['s' => 16, 't' => 'Hibiscus'],
            'b94e48' => ['s' => 16, 't' => 'Chestnut'],
            'bb3385' => ['s' => 16, 't' => 'Medium Red Violet'],
            'c04737' => ['s' => 16, 't' => 'Mojo'],
            'c32148' => ['s' => 16, 't' => 'Maroon Flush'],
            'c45655' => ['s' => 16, 't' => 'Fuzzy Wuzzy Brown'],
            'c54b8c' => ['s' => 16, 't' => 'Mulberry'],
            'c62d42' => ['s' => 16, 't' => 'Brick Red'],
            'c6726b' => ['s' => 16, 't' => 'Contessa'],
            'c71585' => ['s' => 16, 't' => 'Red Violet'],
            'cd5c5c' => ['s' => 16, 't' => 'Chestnut Rose'],
            'd94972' => ['s' => 16, 't' => 'Cabaret'],
            'da3287' => ['s' => 16, 't' => 'Cerise'],
            'da5b38' => ['s' => 16, 't' => 'Flame Pea'],
            'da6a41' => ['s' => 16, 't' => 'Red Damask'],
            'db5079' => ['s' => 16, 't' => 'Cranberry'],
            'de3163' => ['s' => 16, 't' => 'Cerise Red'],
            'de6360' => ['s' => 16, 't' => 'Roman'],
            'e16865' => ['s' => 16, 't' => 'Sunglo'],
            'e25465' => ['s' => 16, 't' => 'Mandy'],
            'e30b5c' => ['s' => 16, 't' => 'Razzmatazz'],
            'e52b50' => ['s' => 16, 't' => 'Amaranth'],
            'b57281' => ['s' => 18, 't' => 'Turkish Rose'],
            'bb8983' => ['s' => 18, 't' => 'Brandy Rose'],
            'bd978e' => ['s' => 18, 't' => 'Quicksand'],
            'c08081' => ['s' => 18, 't' => 'Old Rose'],
            'c69191' => ['s' => 18, 't' => 'Oriental Pink'],
            'c9b29b' => ['s' => 18, 't' => 'Rodeo Dust'],
            'cb8fa9' => ['s' => 18, 't' => 'Viola'],
            'cc8899' => ['s' => 18, 't' => 'Puce'],
            'cfa39d' => ['s' => 18, 't' => 'Eunry'],
            'd06da1' => ['s' => 18, 't' => 'Hopbush'],
            'd29eaa' => ['s' => 18, 't' => 'Careys Pink'],
            'd47494' => ['s' => 18, 't' => 'Charm'],
            'd591a4' => ['s' => 18, 't' => 'Can Can'],
            'd69188' => ['s' => 18, 't' => 'My Pink'],
            'd7837f' => ['s' => 18, 't' => 'New York Pink'],
            'd99376' => ['s' => 18, 't' => 'Burning Sand'],
            'd9b99b' => ['s' => 18, 't' => 'Cameo'],
            'db9690' => ['s' => 18, 't' => 'Petite Orchid'],
            'e47698' => ['s' => 18, 't' => 'Deep Blush'],
            'e79f8c' => ['s' => 18, 't' => 'Tonys Pink'],
            'ea88a8' => ['s' => 18, 't' => 'Carissma'],
            'ed989e' => ['s' => 18, 't' => 'Sea Pink'],
            'e292c0' => ['s' => 19, 't' => 'Shocking'],
            'e29cd2' => ['s' => 19, 't' => 'Light Orchid'],
            'e79fc4' => ['s' => 19, 't' => 'Kobi'],
            'e8b9b3' => ['s' => 19, 't' => 'Shilo'],
            'f091a9' => ['s' => 19, 't' => 'Mauvelous'],
            'f19bab' => ['s' => 19, 't' => 'Wewak'],
            'f6a4c9' => ['s' => 19, 't' => 'Illusion'],
            'f77fbe' => ['s' => 19, 't' => 'Persian Pink'],
            'fba0e3' => ['s' => 19, 't' => 'Lavender Rose'],
            'fbaed2' => ['s' => 19, 't' => 'Lavender Pink'],
            'fbb2a3' => ['s' => 19, 't' => 'Rose Bud'],
            'fd9fa2' => ['s' => 19, 't' => 'Sweet Pink'],
            'febaad' => ['s' => 19, 't' => 'Melon'],
            'ff91a4' => ['s' => 19, 't' => 'Pink Salmon'],
            'ffa6c9' => ['s' => 19, 't' => 'Carnation Pink'],
            'ffb0ac' => ['s' => 19, 't' => 'Cornflower Lilac'],
            'ffb1b3' => ['s' => 19, 't' => 'Sundown'],
            'e9cecd' => ['s' => 20, 't' => 'Oyster Pink'],
            'eccdb9' => ['s' => 20, 't' => 'Just Right'],
            'eec1be' => ['s' => 20, 't' => 'Beauty Bush'],
            'eed9c4' => ['s' => 20, 't' => 'Almond'],
            'f3d9df' => ['s' => 20, 't' => 'Vanilla Ice'],
            'f5e9d3' => ['s' => 20, 't' => 'Albescent White'],
            'f7c8da' => ['s' => 20, 't' => 'Azalea'],
            'f7dbe6' => ['s' => 20, 't' => 'We Peep'],
            'f8c3df' => ['s' => 20, 't' => 'Chantilly'],
            'f8d9e9' => ['s' => 20, 't' => 'Cherub'],
            'faeccc' => ['s' => 20, 't' => 'Champagne'],
            'fbbeda' => ['s' => 20, 't' => 'Cupid'],
            'fbcce7' => ['s' => 20, 't' => 'Classic Rose'],
            'fdd7e4' => ['s' => 20, 't' => 'Pig Pink'],
            'fde1dc' => ['s' => 20, 't' => 'Cinderella'],
            'feefce' => ['s' => 20, 't' => 'Oasis'],
            'fef3d8' => ['s' => 20, 't' => 'Bleach White'],
            'fef4db' => ['s' => 20, 't' => 'Half Spanish White'],
            'ffb7d5' => ['s' => 20, 't' => 'Cotton Candy'],
            'ffc0cb' => ['s' => 20, 't' => 'Pink'],
            'ffc3c0' => ['s' => 20, 't' => 'Your Pink'],
            'ffd1dc' => ['s' => 20, 't' => 'Pastel Pink'],
            'ffd8d9' => ['s' => 20, 't' => 'Cosmos'],
            'ffdcd6' => ['s' => 20, 't' => 'Peach Schnapps'],
            'ffddcd' => ['s' => 20, 't' => 'Tuft Bush'],
            'ffddcf' => ['s' => 20, 't' => 'Watusi'],
            'ffddf4' => ['s' => 20, 't' => 'Pink Lace'],
            'ffe1df' => ['s' => 20, 't' => 'Pippin'],
            'ffe1f2' => ['s' => 20, 't' => 'Pale Rose'],
            'ffe2c5' => ['s' => 20, 't' => 'Negroni'],
            'ffe6c7' => ['s' => 20, 't' => 'Tequila'],
            'ffead4' => ['s' => 20, 't' => 'Karry'],
            'ffeed8' => ['s' => 20, 't' => 'Derby'],
            'ffefd5' => ['s' => 20, 't' => 'Papaya Whip'],
            'fff0db' => ['s' => 20, 't' => 'Peach Cream'],
            'fff1d8' => ['s' => 20, 't' => 'Pink Lady'],
            'fff4dd' => ['s' => 20, 't' => 'Egg Sour'],
            'fff4e0' => ['s' => 20, 't' => 'Sazerac'],
            'fff6d4' => ['s' => 20, 't' => 'Milk Punch'],
            'f400a1' => ['s' => 17, 't' => 'Hollywood Cerise'],
            'f64a8a' => ['s' => 17, 't' => 'French Rose'],
            'f653a6' => ['s' => 17, 't' => 'Brilliant Rose'],
            'f7468a' => ['s' => 17, 't' => 'Violet Red'],
            'f95a61' => ['s' => 17, 't' => 'Carnation'],
            'fb607f' => ['s' => 17, 't' => 'Brink Pink'],
            'fc0fc0' => ['s' => 17, 't' => 'Shocking Pink'],
            'fd5b78' => ['s' => 17, 't' => 'Wild Watermelon'],
            'fe28a2' => ['s' => 17, 't' => 'Persian Rose'],
            'ff007f' => ['s' => 17, 't' => 'Rose'],
            'ff00cc' => ['s' => 17, 't' => 'Purple Pizzazz'],
            'ff3399' => ['s' => 17, 't' => 'Wild Strawberry'],
            'ff33cc' => ['s' => 17, 't' => 'Razzle Dazzle Rose'],
            'ff355e' => ['s' => 17, 't' => 'Radical Red'],
            'ff69b4' => ['s' => 17, 't' => 'Hot Pink'],
            'ac9e22' => ['s' => 31, 't' => 'Lemon Ginger'],
            'af9f1c' => ['s' => 31, 't' => 'Lucky'],
            'b38007' => ['s' => 31, 't' => 'Hot Toddy'],
            'b3c110' => ['s' => 31, 't' => 'La Rioja'],
            'b7a214' => ['s' => 31, 't' => 'Sahara'],
            'b98d28' => ['s' => 31, 't' => 'Marigold'],
            'ba6f1e' => ['s' => 31, 't' => 'Bourbon'],
            'ba7f03' => ['s' => 31, 't' => 'Pirate Gold'],
            'c1a004' => ['s' => 31, 't' => 'Buddha Gold'],
            'c26b03' => ['s' => 31, 't' => 'Indochine'],
            'c59922' => ['s' => 31, 't' => 'Nugget'],
            'c8a528' => ['s' => 31, 't' => 'Hokey Pokey'],
            'c96323' => ['s' => 31, 't' => 'Piper'],
            'c99415' => ['s' => 31, 't' => 'Pizza'],
            'cc5500' => ['s' => 31, 't' => 'Burnt Orange'],
            'cc7722' => ['s' => 31, 't' => 'Ochre'],
            'cd5700' => ['s' => 31, 't' => 'Tenn'],
            'cd8429' => ['s' => 31, 't' => 'Brandy Punch'],
            'd05f04' => ['s' => 31, 't' => 'Red Stage'],
            'd07d12' => ['s' => 31, 't' => 'Meteor'],
            'd18f1b' => ['s' => 31, 't' => 'Geebung'],
            'd2691e' => ['s' => 31, 't' => 'Hot Cinnamon'],
            'da6304' => ['s' => 31, 't' => 'Bamboo'],
            'daa520' => ['s' => 31, 't' => 'Golden Grass'],
            'dcb20c' => ['s' => 31, 't' => 'Galliano'],
            'e28913' => ['s' => 31, 't' => 'Golden Bell'],
            'e29418' => ['s' => 31, 't' => 'Dixie'],
            'e49b0f' => ['s' => 31, 't' => 'Gamboge'],
            'e5841b' => ['s' => 31, 't' => 'Zest'],
            'e77200' => ['s' => 31, 't' => 'Mango Tango'],
            'e7730a' => ['s' => 31, 't' => 'Christine'],
            'e96e00' => ['s' => 31, 't' => 'Clementine'],
            'e97c07' => ['s' => 31, 't' => 'Tahiti Gold'],
            'ed7a1c' => ['s' => 31, 't' => 'Tango'],
            'ed9121' => ['s' => 31, 't' => 'Carrot Orange'],
            'f18200' => ['s' => 31, 't' => 'Gold Drop'],
            'f28500' => ['s' => 31, 't' => 'Tangerine'],
            'f77703' => ['s' => 31, 't' => 'Chilean Fire'],
            'fa7814' => ['s' => 31, 't' => 'Ecstasy'],
            'fd7c07' => ['s' => 31, 't' => 'Sorbus'],
            'ff6600' => ['s' => 31, 't' => 'Blaze Orange'],
            'ff681f' => ['s' => 31, 't' => 'Orange'],
            'ff7034' => ['s' => 31, 't' => 'Burning Orange'],
            'ff7518' => ['s' => 31, 't' => 'Pumpkin'],
            'ff7d07' => ['s' => 31, 't' => 'Flamenco'],
            'ff7f00' => ['s' => 31, 't' => 'Flush Orange'],
            'cfb53b' => ['s' => 33, 't' => 'Old Gold'],
            'd1e231' => ['s' => 33, 't' => 'Pear'],
            'deba13' => ['s' => 33, 't' => 'Gold Tips'],
            'e0b646' => ['s' => 33, 't' => 'Anzac'],
            'e4d422' => ['s' => 33, 't' => 'Sunflower'],
            'e89928' => ['s' => 33, 't' => 'Fire Bush'],
            'eab33b' => ['s' => 33, 't' => 'Tulip Tree'],
            'eca927' => ['s' => 33, 't' => 'Fuel Yellow'],
            'ef863f' => ['s' => 33, 't' => 'Jaffa'],
            'f0d52d' => ['s' => 33, 't' => 'Golden Dream'],
            'f3ad16' => ['s' => 33, 't' => 'Buttercup'],
            'f4c430' => ['s' => 33, 't' => 'Saffron'],
            'fba129' => ['s' => 33, 't' => 'Sea Buckthorn'],
            'fc9c1d' => ['s' => 33, 't' => 'Tree Poppy'],
            'fcc01e' => ['s' => 33, 't' => 'Lightning Yellow'],
            'fd7b33' => ['s' => 33, 't' => 'Crusta'],
            'fed33c' => ['s' => 33, 't' => 'Bright Sun'],
            'ff9933' => ['s' => 33, 't' => 'Neon Carrot'],
            'ff9e2c' => ['s' => 33, 't' => 'Sunshade'],
            'ffae42' => ['s' => 33, 't' => 'Yellow Orange'],
            'ffb31f' => ['s' => 33, 't' => 'My Sin'],
            'ffcc33' => ['s' => 33, 't' => 'Sunglow'],
            'd2da97' => ['s' => 35, 't' => 'Deco'],
            'd5d195' => ['s' => 35, 't' => 'Winter Hazel'],
            'd7c498' => ['s' => 35, 't' => 'Pavlova'],
            'dec196' => ['s' => 35, 't' => 'Brandy'],
            'ded4a4' => ['s' => 35, 't' => 'Sapling'],
            'e0c095' => ['s' => 35, 't' => 'Calico'],
            'e4d69b' => ['s' => 35, 't' => 'Zombie'],
            'e5d8af' => ['s' => 35, 't' => 'Hampton'],
            'e6be8a' => ['s' => 35, 't' => 'Gold Sand'],
            'e6bea5' => ['s' => 35, 't' => 'Cashmere'],
            'e7cd8c' => ['s' => 35, 't' => 'Putty'],
            'ebc2af' => ['s' => 35, 't' => 'Zinnwaldite'],
            'ece090' => ['s' => 35, 't' => 'Wild Rice'],
            'edc9af' => ['s' => 35, 't' => 'Desert Sand'],
            'edcdab' => ['s' => 35, 't' => 'Pancho'],
            'edea99' => ['s' => 35, 't' => 'Primrose'],
            'eed794' => ['s' => 35, 't' => 'Chalky'],
            'eedc82' => ['s' => 35, 't' => 'Flax'],
            'f0dc82' => ['s' => 35, 't' => 'Buff'],
            'f0e68c' => ['s' => 35, 't' => 'Khaki'],
            'f1e788' => ['s' => 35, 't' => 'Sahara Sand'],
            'f2c3b2' => ['s' => 35, 't' => 'Mandys Pink'],
            'f3d69d' => ['s' => 35, 't' => 'New Orleans'],
            'f5c999' => ['s' => 35, 't' => 'Manhattan'],
            'f5d5a0' => ['s' => 35, 't' => 'Maize'],
            'f5e7a2' => ['s' => 35, 't' => 'Sandwisp'],
            'f8db9d' => ['s' => 35, 't' => 'Marzipan'],
            'fad3a2' => ['s' => 35, 't' => 'Corvette'],
            'fbceb1' => ['s' => 35, 't' => 'Apricot Peach'],
            'fbea8c' => ['s' => 35, 't' => 'Sweet Corn'],
            'fcda98' => ['s' => 35, 't' => 'Cherokee'],
            'fdd5b1' => ['s' => 35, 't' => 'Light Apricot'],
            'fde295' => ['s' => 35, 't' => 'Golden Glow'],
            'fedb8d' => ['s' => 35, 't' => 'Salomie'],
            'ffc0a8' => ['s' => 35, 't' => 'Wax Flower'],
            'ffcba4' => ['s' => 35, 't' => 'Flesh'],
            'ffcc99' => ['s' => 35, 't' => 'Peach Orange'],
            'ffcd8c' => ['s' => 35, 't' => 'Chardonnay'],
            'ffd2b7' => ['s' => 35, 't' => 'Romantic'],
            'ffd38c' => ['s' => 35, 't' => 'Grandis'],
            'ffdead' => ['s' => 35, 't' => 'Navajo White'],
            'ffe5a0' => ['s' => 35, 't' => 'Cream Brulee'],
            'dcd747' => ['s' => 34, 't' => 'Wattle'],
            'dfcd6f' => ['s' => 34, 't' => 'Chenin'],
            'e9d75a' => ['s' => 34, 't' => 'Confetti'],
            'eac674' => ['s' => 34, 't' => 'Rob Roy'],
            'ecc54e' => ['s' => 34, 't' => 'Ronchi'],
            'f4a460' => ['s' => 34, 't' => 'Sandy brown'],
            'f5c85c' => ['s' => 34, 't' => 'Cream Can'],
            'f7b668' => ['s' => 34, 't' => 'Rajah'],
            'f8b853' => ['s' => 34, 't' => 'Casablanca'],
            'f8dd5c' => ['s' => 34, 't' => 'Energy Yellow'],
            'f9bf58' => ['s' => 34, 't' => 'Saffron Mango'],
            'fa9d5a' => ['s' => 34, 't' => 'Tan Hide'],
            'fcd667' => ['s' => 34, 't' => 'Goldenrod'],
            'fed85d' => ['s' => 34, 't' => 'Dandelion'],
            'ffb555' => ['s' => 34, 't' => 'Texas Rose'],
            'ffb97b' => ['s' => 34, 't' => 'Macaroni and Cheese'],
            'ffbd5f' => ['s' => 34, 't' => 'Koromiko'],
            'ffcc5c' => ['s' => 34, 't' => 'Golden Tainoi'],
            'ffdb58' => ['s' => 34, 't' => 'Mustard'],
            'fbac13' => ['s' => 32, 't' => 'Sun'],
            'fe9d04' => ['s' => 32, 't' => 'California'],
            'fea904' => ['s' => 32, 't' => 'Yellow Sea'],
            'ff9000' => ['s' => 32, 't' => 'Pizazz'],
            'ff910f' => ['s' => 32, 't' => 'West Side'],
            'ffa000' => ['s' => 32, 't' => 'Orange Peel'],
            'ffa500' => ['s' => 32, 't' => 'Web Orange'],
            'ffba00' => ['s' => 32, 't' => 'Selective Yellow'],
            'bbd009' => ['s' => 26, 't' => 'Rio Grande'],
            'd4cd16' => ['s' => 26, 't' => 'Bird Flower'],
            'ded717' => ['s' => 26, 't' => 'Barberry'],
            'e7bf05' => ['s' => 26, 't' => 'Corn'],
            'f4d81c' => ['s' => 26, 't' => 'Ripe Lemon'],
            'fcd917' => ['s' => 26, 't' => 'Candlelight'],
            'ffbf00' => ['s' => 26, 't' => 'Amber'],
            'ffc901' => ['s' => 26, 't' => 'Supernova'],
            'ffd700' => ['s' => 26, 't' => 'Gold'],
            'ffd800' => ['s' => 26, 't' => 'School bus Yellow'],
            'bede0d' => ['s' => 27, 't' => 'Fuego'],
            'c6e610' => ['s' => 27, 't' => 'Las Palmas'],
            'cae00d' => ['s' => 27, 't' => 'Bitter Lemon'],
            'fae600' => ['s' => 27, 't' => 'Turbo'],
            'fde910' => ['s' => 27, 't' => 'Lemon'],
            'ffec13' => ['s' => 27, 't' => 'Broom'],
            'd2f8b0' => ['s' => 30, 't' => 'Gossip'],
            'dcedb4' => ['s' => 30, 't' => 'Caper'],
            'eadab8' => ['s' => 30, 't' => 'Raffia'],
            'ecebbd' => ['s' => 30, 't' => 'Fall Green'],
            'eddcb1' => ['s' => 30, 't' => 'Chamois'],
            'eee3ad' => ['s' => 30, 't' => 'Double Colonial White'],
            'eef0c8' => ['s' => 30, 't' => 'Tahuna Sands'],
            'eef3c3' => ['s' => 30, 't' => 'Tusk'],
            'eeff9a' => ['s' => 30, 't' => 'Jonquil'],
            'f1eec1' => ['s' => 30, 't' => 'Mint Julep'],
            'f1ffad' => ['s' => 30, 't' => 'Tidal'],
            'f1ffc8' => ['s' => 30, 't' => 'Chiffon'],
            'f3e7bb' => ['s' => 30, 't' => 'Sidecar'],
            'f5deb3' => ['s' => 30, 't' => 'Wheat'],
            'f5ffbe' => ['s' => 30, 't' => 'Australian Mint'],
            'f8e4bf' => ['s' => 30, 't' => 'Givry'],
            'f8f99c' => ['s' => 30, 't' => 'Texas'],
            'f8facd' => ['s' => 30, 't' => 'Corn Field'],
            'f8fdd3' => ['s' => 30, 't' => 'Mimosa'],
            'f9e4bc' => ['s' => 30, 't' => 'Dairy Cream'],
            'fadfad' => ['s' => 30, 't' => 'Peach Yellow'],
            'faeab9' => ['s' => 30, 't' => 'Astra'],
            'faffa4' => ['s' => 30, 't' => 'Milan'],
            'fbe7b2' => ['s' => 30, 't' => 'Banana Mania'],
            'fbffba' => ['s' => 30, 't' => 'Shalimar'],
            'fcf4d0' => ['s' => 30, 't' => 'Double Pearl Lusta'],
            'fdf6d3' => ['s' => 30, 't' => 'Half Colonial White'],
            'fdf7ad' => ['s' => 30, 't' => 'Drover'],
            'fdfeb8' => ['s' => 30, 't' => 'Pale Prim'],
            'fdffd5' => ['s' => 30, 't' => 'Cumulus'],
            'fee5ac' => ['s' => 30, 't' => 'Cape Honey'],
            'fef2c7' => ['s' => 30, 't' => 'Beeswax'],
            'fef4cc' => ['s' => 30, 't' => 'Pipi'],
            'ffddaf' => ['s' => 30, 't' => 'Caramel'],
            'ffdeb3' => ['s' => 30, 't' => 'Frangipani'],
            'ffe5b4' => ['s' => 30, 't' => 'Peach'],
            'ffeac8' => ['s' => 30, 't' => 'Sandy Beach'],
            'ffedbc' => ['s' => 30, 't' => 'Colonial White'],
            'ffefa1' => ['s' => 30, 't' => 'Vis Vis'],
            'ffefc1' => ['s' => 30, 't' => 'Egg White'],
            'fff1b5' => ['s' => 30, 't' => 'Buttermilk'],
            'fff39d' => ['s' => 30, 't' => 'Picasso'],
            'fff4ce' => ['s' => 30, 't' => 'Barley White'],
            'fff8d1' => ['s' => 30, 't' => 'Baja White'],
            'fffacd' => ['s' => 30, 't' => 'Lemon Chiffon'],
            'fffc99' => ['s' => 30, 't' => 'Witch Haze'],
            'fffdd0' => ['s' => 30, 't' => 'Cream'],
            'ffff99' => ['s' => 30, 't' => 'Pale Canary'],
            'ffffb4' => ['s' => 30, 't' => 'Portafino'],
            'dfff00' => ['s' => 28, 't' => 'Chartreuse Yellow'],
            'f5fb3d' => ['s' => 28, 't' => 'Golden Fizz'],
            'ffff00' => ['s' => 28, 't' => 'Yellow'],
            'ffff66' => ['s' => 28, 't' => 'Laser Lemon'],
            'e3f988' => ['s' => 29, 't' => 'Mindaro'],
            'ecf245' => ['s' => 29, 't' => 'Starship'],
            'edfc84' => ['s' => 29, 't' => 'Honeysuckle'],
            'eeef78' => ['s' => 29, 't' => 'Manz'],
            'f0db7d' => ['s' => 29, 't' => 'Golden Sand'],
            'f3fb62' => ['s' => 29, 't' => 'Canary'],
            'f9e663' => ['s' => 29, 't' => 'Portica'],
            'f9ff8b' => ['s' => 29, 't' => 'Dolly'],
            'fbe870' => ['s' => 29, 't' => 'Marigold Yellow'],
            'fbe96c' => ['s' => 29, 't' => 'Festival'],
            'fbec5d' => ['s' => 29, 't' => 'Candy Corn'],
            'ffe772' => ['s' => 29, 't' => 'Kournikova'],
            'fff14f' => ['s' => 29, 't' => 'Gorse'],
            'fff46e' => ['s' => 29, 't' => 'Paris Daisy'],
            'dafaff' => ['s' => 46, 't' => 'Oyster Bay'],
            'e0ffff' => ['s' => 46, 't' => 'Baby Blue'],
            'e5f9f6' => ['s' => 46, 't' => 'Polar'],
            'e6ffff' => ['s' => 46, 't' => 'Tranquil'],
            'e7f8ff' => ['s' => 46, 't' => 'Lily White'],
            'e7feff' => ['s' => 46, 't' => 'Bubbles'],
            'e9fffd' => ['s' => 46, 't' => 'Clear Day'],
            'eaf6ff' => ['s' => 46, 't' => 'Solitude'],
            'eaf9f5' => ['s' => 46, 't' => 'Aqua Spring'],
            'eafffe' => ['s' => 46, 't' => 'Dew'],
            'edf5f5' => ['s' => 46, 't' => 'Aqua Haze'],
            'edf6ff' => ['s' => 46, 't' => 'Zumthor'],
            'edf9f1' => ['s' => 46, 't' => 'Narvik'],
            'eef6f7' => ['s' => 46, 't' => 'Catskill White'],
            'eefdff' => ['s' => 46, 't' => 'Twilight Blue'],
            'eff2f3' => ['s' => 46, 't' => 'Porcelain'],
            'f0eefd' => ['s' => 46, 't' => 'Selago'],
            'f0eeff' => ['s' => 46, 't' => 'Titan White'],
            'f0f8ff' => ['s' => 46, 't' => 'Alice Blue'],
            'f0fcea' => ['s' => 46, 't' => 'Feta'],
            'f1e9ff' => ['s' => 46, 't' => 'Blue Chalk'],
            'f1f7f2' => ['s' => 46, 't' => 'Saltpan'],
            'f2f2f2' => ['s' => 46, 't' => 'Concrete'],
            'f2fafa' => ['s' => 46, 't' => 'Black Squeeze'],
            'f4f4f4' => ['s' => 46, 't' => 'Wild Sand'],
            'f4f8ff' => ['s' => 46, 't' => 'Zircon'],
            'f6f7f7' => ['s' => 46, 't' => 'Black Haze'],
            'f7f5fa' => ['s' => 46, 't' => 'Whisper'],
            'f7faf7' => ['s' => 46, 't' => 'Snow Drift'],
            'f8f4ff' => ['s' => 46, 't' => 'Magnolia'],
            'f8f6f1' => ['s' => 46, 't' => 'Spring Wood'],
            'f8f7fc' => ['s' => 46, 't' => 'White Lilac'],
            'f8f8f7' => ['s' => 46, 't' => 'Desert Storm'],
            'f9eaf3' => ['s' => 46, 't' => 'Amour'],
            'f9f8e4' => ['s' => 46, 't' => 'Rum Swizzle'],
            'f9fff6' => ['s' => 46, 't' => 'Sugar Cane'],
            'faf3f0' => ['s' => 46, 't' => 'Fantasy'],
            'fafafa' => ['s' => 46, 't' => 'Alabaster'],
            'fafde4' => ['s' => 46, 't' => 'Hint of Yellow'],
            'fbf9f9' => ['s' => 46, 't' => 'Hint of Red'],
            'fcf8f7' => ['s' => 46, 't' => 'Vista White'],
            'fcfbf3' => ['s' => 46, 't' => 'Bianca'],
            'fcffe7' => ['s' => 46, 't' => 'China Ivory'],
            'fcfff9' => ['s' => 46, 't' => 'Ceramic'],
            'fdf5e6' => ['s' => 46, 't' => 'Old Lace'],
            'feebf3' => ['s' => 46, 't' => 'Remy'],
            'fef0ec' => ['s' => 46, 't' => 'Bridesmaid'],
            'fef4f8' => ['s' => 46, 't' => 'Wisp Pink'],
            'fef5f1' => ['s' => 46, 't' => 'Provincial Pink'],
            'fef8e2' => ['s' => 46, 't' => 'Solitaire'],
            'fef8ff' => ['s' => 46, 't' => 'White Pointer'],
            'fef9e3' => ['s' => 46, 't' => 'Off Yellow'],
            'fefced' => ['s' => 46, 't' => 'Orange White'],
            'ffefec' => ['s' => 46, 't' => 'Fair Pink'],
            'fff0f5' => ['s' => 46, 't' => 'Lavender blush'],
            'fff1ee' => ['s' => 46, 't' => 'Forget Me Not'],
            'fff1f9' => ['s' => 46, 't' => 'Tutu'],
            'fff3f1' => ['s' => 46, 't' => 'Chardon'],
            'fff4e8' => ['s' => 46, 't' => 'Serenade'],
            'fff4f3' => ['s' => 46, 't' => 'Chablis'],
            'fff5ee' => ['s' => 46, 't' => 'Seashell Peach'],
            'fff5f3' => ['s' => 46, 't' => 'Sauvignon'],
            'fff6f5' => ['s' => 46, 't' => 'Rose White'],
            'fff9e2' => ['s' => 46, 't' => 'Gin Fizz'],
            'fff9e6' => ['s' => 46, 't' => 'Early Dawn'],
            'fffaf4' => ['s' => 46, 't' => 'Bridal Heath'],
            'fffbdc' => ['s' => 46, 't' => 'Scotch Mist'],
            'fffbf9' => ['s' => 46, 't' => 'Soapstone'],
            'fffcea' => ['s' => 46, 't' => 'Buttery White'],
            'fffcee' => ['s' => 46, 't' => 'Island Spice'],
            'fffde6' => ['s' => 46, 't' => 'Chilean Heath'],
            'fffde8' => ['s' => 46, 't' => 'Travertine'],
            'fffdf3' => ['s' => 46, 't' => 'Orchid White'],
            'fffdf4' => ['s' => 46, 't' => 'Quarter Pearl Lusta'],
            'fffee1' => ['s' => 46, 't' => 'Half and Half'],
            'fffeec' => ['s' => 46, 't' => 'Apricot White'],
            'fffef0' => ['s' => 46, 't' => 'Rice Cake'],
            'fffef6' => ['s' => 46, 't' => 'Black White'],
            'fffefd' => ['s' => 46, 't' => 'Romance'],
            'fffff0' => ['s' => 46, 't' => 'Ivory'],
            'ffffff' => ['s' => 46, 't' => 'White']
        ]
    ];
}